// AUTO-GENERATED from backrooms.db (Backrooms Wiki ARPG curation). Do not edit by hand.
// Regenerate with: python3 scripts/gen_gamedata.py

export type SceneKind = 'corridor' | 'office' | 'hotel' | 'dark' | 'water' | 'cave' | 'suburb' | 'field' | 'digital' | 'ruins' | 'void' | 'neon';
export interface Level { id: string; name: string; desc: string; hook: string; unlockCost: number; mult: number; rating: number; scene: SceneKind; verb: string; icon: string; hue: number; }
export interface Generator { id: string; name: string; desc: string; hook: string; baseCost: number; baseProd: number; rating: number; }
export type GearSlot = 'Weapon' | 'Light' | 'Armor' | 'Trinket';
export type Rarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary' | 'mythic';
export interface GearStats { clickMult: number; prodMult: number; luck: number; crit: number; }
export interface Gear { id: string; name: string; desc: string; hook: string; slot: GearSlot; rarity: Rarity; cost: number; stats: GearStats; rating: number; levelIndex: number; abyssOnly?: boolean; }
export interface Encounter { id: string; name: string; desc: string; hook: string; boss: boolean; rating: number; }
export interface Finale { id: string; name: string; desc: string; hook: string; rating: number; }
export interface Phenomenon { id: string; name: string; desc: string; hook: string; effect: string; label: string; rating: number; }

export const LEVELS: Level[] = [
  {
    "id": "level-0",
    "name": "Level 0 - 'Threshold'",
    "desc": "Tutorial labyrinth built around isolation, attrition, shifting rooms, and architectural aberrations.",
    "hook": "Rearrange unseen corridors while dehydration and isolation pressure the player to keep moving.",
    "unlockCost": 0,
    "mult": 1.0,
    "rating": 167,
    "scene": "corridor",
    "verb": "PHASE",
    "icon": "\u259a",
    "hue": 0
  },
  {
    "id": "level-1",
    "name": "Level 1 - 'Habitable Zone'",
    "desc": "First major inhabited zone with loot crates, sectors, settlements, traders, and intermittent danger.",
    "hook": "Use settlements as the first trade hub while flickering sectors become timed loot runs.",
    "unlockCost": 442,
    "mult": 2.0,
    "rating": 164,
    "scene": "suburb",
    "verb": "SCAVENGE",
    "icon": "\u2302",
    "hue": 47
  },
  {
    "id": "level-4",
    "name": "Level 4 - 'Abandoned Office'",
    "desc": "Abandoned-office biome with deceptive black windows and multiple safe-zone factions.",
    "hook": "Alternate calm offices and lethal window traps around faction outposts.",
    "unlockCost": 1666.7,
    "mult": 3.1,
    "rating": 203,
    "scene": "office",
    "verb": "RUMMAGE",
    "icon": "\u25a6",
    "hue": 94
  },
  {
    "id": "level-5",
    "name": "Level 5 - 'Terror Hotel'",
    "desc": "Multi-wing hotel dungeon with faction pockets, a boiler descent, and the Beast of Level 5.",
    "hook": "Make each hotel wing a distinct dungeon layer culminating in the Beast's domain.",
    "unlockCost": 5591.45,
    "mult": 4.25,
    "rating": 222,
    "scene": "hotel",
    "verb": "CREEP",
    "icon": "\ud83d\udeaa",
    "hue": 141
  },
  {
    "id": "level-6",
    "name": "Level 6 - 'Lights Out'",
    "desc": "Darkness and sound-driven stealth zone with mimicry and sanity pressure.",
    "hook": "Navigate by sound while hostile mimicry makes every audio cue uncertain.",
    "unlockCost": 17673.3,
    "mult": 5.44,
    "rating": 177,
    "scene": "dark",
    "verb": "FEEL",
    "icon": "\u25d0",
    "hue": 188
  },
  {
    "id": "level-7",
    "name": "Level 7 - 'Thalassophobia'",
    "desc": "Open-water dungeon built around oxygen, light, depth, and deep-sea enemies.",
    "hook": "Trade light and oxygen for deeper loot routes through hostile water.",
    "unlockCost": 55629.7,
    "mult": 6.68,
    "rating": 148,
    "scene": "water",
    "verb": "WADE",
    "icon": "\u2248",
    "hue": 235
  },
  {
    "id": "level-8",
    "name": "Level 8 - 'Cave Systems'",
    "desc": "Branching cave biome with hostile ecology, difficult terrain, roads, and faction outposts.",
    "hook": "Use speleology tools and outpost routes to push through an enemy-rich cave network.",
    "unlockCost": 178249,
    "mult": 7.94,
    "rating": 140,
    "scene": "cave",
    "verb": "CRAWL",
    "icon": "\u26f0",
    "hue": 282
  },
  {
    "id": "level-9",
    "name": "Level 9 - 'The Suburbs'",
    "desc": "Hostile midnight suburb designed for house-to-house looting and stalking encounters.",
    "hook": "Turn each house into a risky loot pocket within a predator-controlled overworld.",
    "unlockCost": 581912,
    "mult": 9.24,
    "rating": 184,
    "scene": "suburb",
    "verb": "SCAVENGE",
    "icon": "\u2302",
    "hue": 329
  },
  {
    "id": "level-10",
    "name": "Level 10 - 'Bumper Crop'",
    "desc": "Farmland recovery biome supporting foraging, food production, and settlements.",
    "hook": "Use farms as a consumable-production region threatened by weather and supply quests.",
    "unlockCost": 1923920,
    "mult": 10.56,
    "rating": 114,
    "scene": "field",
    "verb": "FORAGE",
    "icon": "\u2766",
    "hue": 16
  },
  {
    "id": "level-12",
    "name": "Level 12 - 'Matrix'",
    "desc": "Self-censoring reality where observation and recording fail.",
    "hook": "Hide state from maps and recordings so players solve the zone through indirect observation.",
    "unlockCost": 6405690,
    "mult": 11.9,
    "rating": 120,
    "scene": "digital",
    "verb": "GLITCH",
    "icon": "\u2593",
    "hue": 63
  },
  {
    "id": "level-14",
    "name": "Level 14 - 'Paradise'",
    "desc": "Seductive false paradise whose crimson forest inflicts escalating mental corruption.",
    "hook": "Reward staying in a beautiful high-loot forest while corruption steadily distorts choices.",
    "unlockCost": 21401400,
    "mult": 13.27,
    "rating": 228,
    "scene": "field",
    "verb": "FORAGE",
    "icon": "\u2766",
    "hue": 110
  },
  {
    "id": "level-22",
    "name": "Level 22 - 'Ruins Left Behind'",
    "desc": "Abandoned parking-city ruins suited to scavenging and environmental storytelling.",
    "hook": "Reconstruct the vanished settlement through salvage, ruins, and layered records.",
    "unlockCost": 71613900,
    "mult": 14.66,
    "rating": 115,
    "scene": "ruins",
    "verb": "SIFT",
    "icon": "\u25c8",
    "hue": 157
  },
  {
    "id": "level-23",
    "name": "Level 23 - 'The Petrified Garden'",
    "desc": "Planetoid-scale living dungeon with glow rooms, ancient ruins, sentries, and giants.",
    "hook": "Build long expeditions around living terrain, ancient defenses, and landmark-scale bosses.",
    "unlockCost": 239797000,
    "mult": 16.06,
    "rating": 120,
    "scene": "field",
    "verb": "FORAGE",
    "icon": "\u2766",
    "hue": 204
  },
  {
    "id": "level-37",
    "name": "Level 37 - 'Sublimity'",
    "desc": "Calm Poolrooms biome with healing water, irregular geometry, and dangerous submerged pits.",
    "hook": "Offer healing and respite while hiding traversal puzzles beneath apparently safe pools.",
    "unlockCost": 803177000,
    "mult": 17.49,
    "rating": 308,
    "scene": "void",
    "verb": "DRIFT",
    "icon": "\u2726",
    "hue": 251
  },
  {
    "id": "level-69",
    "name": "Level 69 - 'The Road Trip of Affliction'",
    "desc": "Vehicle-bound road survival map with fog, finite light, and pursuit encounters.",
    "hook": "Make fuel, visibility, and roadside stops the resource loop of a continuous chase.",
    "unlockCost": 2690460000,
    "mult": 18.93,
    "rating": 118,
    "scene": "ruins",
    "verb": "SIFT",
    "icon": "\u25c8",
    "hue": 298
  },
  {
    "id": "level-200",
    "name": "Level 200 - 'Home'",
    "desc": "Large uncanny town supporting NPC services, social play, and a hidden-state mystery.",
    "hook": "Use a comfortable civic hub whose normality slowly reveals a concealed world state.",
    "unlockCost": 9012800000,
    "mult": 20.4,
    "rating": 192,
    "scene": "suburb",
    "verb": "SCAVENGE",
    "icon": "\u2302",
    "hue": 345
  },
  {
    "id": "level-263",
    "name": "Level 263 - 'Untextured'",
    "desc": "Glitched checkerboard space with visual noise, broken geometry, and unstable enemies.",
    "hook": "Let visual corruption alter collision, enemy rules, and navigable geometry.",
    "unlockCost": 30192600000,
    "mult": 21.88,
    "rating": 154,
    "scene": "digital",
    "verb": "GLITCH",
    "icon": "\u2593",
    "hue": 32
  },
  {
    "id": "level-289",
    "name": "Level 289 - 'Overflow'",
    "desc": "Flooded unfinished basement with electrified water, scaffolding, entities, and escape pressure.",
    "hook": "Route players across scaffolds while water level and electrical danger reshape safe paths.",
    "unlockCost": 101145000000,
    "mult": 23.37,
    "rating": 184,
    "scene": "water",
    "verb": "WADE",
    "icon": "\u2248",
    "hue": 79
  },
  {
    "id": "level-404",
    "name": "level 404 - 'my dearly fragmented'",
    "desc": "Endgame anomaly zone built from data fragmentation, memory loss, and broken geometry.",
    "hook": "Fragment the map, codex, and remembered objectives as the player advances.",
    "unlockCost": 338835000000,
    "mult": 24.88,
    "rating": 425,
    "scene": "digital",
    "verb": "GLITCH",
    "icon": "\u2593",
    "hue": 126
  },
  {
    "id": "level-601",
    "name": "Level 601 - 'The End'",
    "desc": "False-exit library with looping geometry, deceptive terminals, ambushes, and fake realities.",
    "hook": "Present convincing exits and system messages that can strand players in deeper loops.",
    "unlockCost": 1135100000000,
    "mult": 26.4,
    "rating": 162,
    "scene": "void",
    "verb": "DRIFT",
    "icon": "\u2726",
    "hue": 173
  },
  {
    "id": "level-906",
    "name": "Level 906 - 'The Cygnus Archive'",
    "desc": "Infinite gothic archive and knowledge hub centered on Blanche, books, and portal lore.",
    "hook": "Turn recovered books into portal access, crafting knowledge, and Blanche reputation.",
    "unlockCost": 3802570000000,
    "mult": 27.94,
    "rating": 179,
    "scene": "void",
    "verb": "DRIFT",
    "icon": "\u2726",
    "hue": 220
  },
  {
    "id": "level-999",
    "name": "Level 999",
    "desc": "Finite monochrome island in a starry void suited to a finale or end-state journey.",
    "hook": "Use desaturation and isolation to stage a reflective endgame destination.",
    "unlockCost": 12738600000000,
    "mult": 29.5,
    "rating": 143,
    "scene": "void",
    "verb": "DRIFT",
    "icon": "\u2726",
    "hue": 267
  },
  {
    "id": "the-hub",
    "name": "Unnumbered Level - 'The Hub'",
    "desc": "Central door nexus for fast travel, faction outposts, and the Keymaster.",
    "hook": "Gate the travel network behind discovered doors, keys, and faction control.",
    "unlockCost": 42674400000000,
    "mult": 31.06,
    "rating": 167,
    "scene": "neon",
    "verb": "SLIP",
    "icon": "\u25c6",
    "hue": 314
  },
  {
    "id": "blue-channel",
    "name": "Unnumbered Level - 'The Blue Channel'",
    "desc": "Inter-level void with swimming-like zero-gravity movement and isolated scene landmarks.",
    "hook": "Let players move between exposed level fragments through a disorienting void.",
    "unlockCost": 142959000000000,
    "mult": 32.64,
    "rating": 160,
    "scene": "water",
    "verb": "WADE",
    "icon": "\u2248",
    "hue": 1
  },
  {
    "id": "red-rooms",
    "name": "Red Rooms",
    "desc": "Level 0 sub-dungeon with mold, communications decay, paranoia, and near-impossible escape.",
    "hook": "Lock escape routes as mold and paranoia intensify during a high-stakes delve.",
    "unlockCost": 478913000000000,
    "mult": 34.23,
    "rating": 114,
    "scene": "neon",
    "verb": "SLIP",
    "icon": "\u25c6",
    "hue": 48
  },
  {
    "id": "manila-room",
    "name": "The Manila Room",
    "desc": "Rare safe room suitable as tutorial archive, meeting point, and checkpoint.",
    "hook": "Use a difficult-to-find refuge to deliver early lore and restore the player.",
    "unlockCost": 1604360000000000,
    "mult": 35.84,
    "rating": 108,
    "scene": "office",
    "verb": "RUMMAGE",
    "icon": "\u25a6",
    "hue": 95
  },
  {
    "id": "level-0-1",
    "name": "Level 0.1 - 'Zenith Station'",
    "desc": "Vast space station and failed wormhole experiment for a science-fiction expedition.",
    "hook": "Explore station systems while reconstructing a disastrous transit experiment.",
    "unlockCost": 5374600000000000,
    "mult": 37.46,
    "rating": 135,
    "scene": "void",
    "verb": "DRIFT",
    "icon": "\u2726",
    "hue": 142
  },
  {
    "id": "level-0-2",
    "name": "Level 0.2 - 'Remodeled Mess'",
    "desc": "Pristine Level 0 variant that destabilizes after physical interaction.",
    "hook": "Make touch itself the trigger that corrupts safe-looking routes and loot rooms.",
    "unlockCost": 18004900000000000,
    "mult": 39.09,
    "rating": 119,
    "scene": "office",
    "verb": "RUMMAGE",
    "icon": "\u25a6",
    "hue": 189
  },
  {
    "id": "level-1-1",
    "name": "Level 1.1 - 'Corrupted Corridor'",
    "desc": "Multi-sector expedition gauntlet with declining supplies and rising enemy density.",
    "hook": "Escalate danger across sectors while denying easy resupply or retreat.",
    "unlockCost": 60316500000000000,
    "mult": 40.73,
    "rating": 116,
    "scene": "digital",
    "verb": "GLITCH",
    "icon": "\u2593",
    "hue": 236
  },
  {
    "id": "level-1-3",
    "name": "Level 1.3 - 'Malignance'",
    "desc": "Healing hospital and contested medical resource with Detox Zones and faction defense.",
    "hook": "Tie healing access to defense events and control of scarce medical zones.",
    "unlockCost": 202060000000000000,
    "mult": 42.38,
    "rating": 118,
    "scene": "dark",
    "verb": "FEEL",
    "icon": "\u25d0",
    "hue": 283
  },
  {
    "id": "level-5-1",
    "name": "Level 5.1 - 'GRAND OPENING OF THE TERROR HOTEL CASINO'",
    "desc": "Casino hub-dungeon with wagers, rare loot, staff NPCs, and Beast encounters.",
    "hook": "Let players wager resources and danger for casino-specific gear and routes.",
    "unlockCost": 676901000000000000,
    "mult": 44.04,
    "rating": 145,
    "scene": "hotel",
    "verb": "CREEP",
    "icon": "\ud83d\udeaa",
    "hue": 330
  },
  {
    "id": "level-6-1",
    "name": "Level 6.1 - 'The Snackrooms'",
    "desc": "Mall-food labyrinth with merchants, consumables, faction bases, and breach events.",
    "hook": "Anchor the food economy in a merchant hub periodically disrupted by hostile breaches.",
    "unlockCost": 2267620000000000000,
    "mult": 45.72,
    "rating": 124,
    "scene": "suburb",
    "verb": "SCAVENGE",
    "icon": "\u2302",
    "hue": 17
  },
  {
    "id": "level-11-3",
    "name": "Level 11.3 - 'The Red Light District'",
    "desc": "Endgame urban zone with psychoactive air, red lightning, and mask-based mitigation.",
    "hook": "Require protective masks while storms and altered perception transform combat.",
    "unlockCost": 7596530000000000000,
    "mult": 47.4,
    "rating": 123,
    "scene": "neon",
    "verb": "SLIP",
    "icon": "\u25c6",
    "hue": 64
  },
  {
    "id": "th3-sh4dy-gr3y",
    "name": "Unnumbered Level - 'Th3 Sh4dy Gr3y'",
    "desc": "Cluster of unstable sublevels with extreme temperatures, factions, and entities.",
    "hook": "Chain mechanically incompatible sublevels into an endgame expedition.",
    "unlockCost": 25448400000000000000,
    "mult": 49.1,
    "rating": 251,
    "scene": "dark",
    "verb": "FEEL",
    "icon": "\u25d0",
    "hue": 111
  },
  {
    "id": "deleted-level-14",
    "name": "Unnumbered Level - 'Deleted Level 14'",
    "desc": "Abandoned military hospital with dangerous medical loot, phasing ghosts, and a route puzzle.",
    "hook": "Use repeatable route patterns to evade phasing enemies and reach surgical loot.",
    "unlockCost": 85252000000000000000,
    "mult": 50.8,
    "rating": 142,
    "scene": "digital",
    "verb": "GLITCH",
    "icon": "\u2593",
    "hue": 158
  },
  {
    "id": "level-611",
    "name": "Level 611 - 'The maze, the creatures, the monster'",
    "desc": "Filthy mixed-architecture maze with structural hazards and a Sentinel boss.",
    "hook": "Telegraph a persistent Sentinel through maze damage before the final confrontation.",
    "unlockCost": 285594000000000000000,
    "mult": 52.52,
    "rating": 131,
    "scene": "cave",
    "verb": "CRAWL",
    "icon": "\u26f0",
    "hue": 205
  }
];

export const GENERATORS: Generator[] = [
  {
    "id": "entity-140",
    "name": "Entity 140 - 'Blanche'",
    "desc": "Archive guardian Blanche is a knowledge-focused quest giver and social NPC.",
    "hook": "Reward book recovery, manners, and lore discovery with knowledge and archive access.",
    "baseCost": 18,
    "baseProd": 0.15,
    "rating": 233
  },
  {
    "id": "entity-71",
    "name": "Entity 71 - 'The Red Knight'",
    "desc": "Roaming champion who can rescue, duel, train, or accompany the player.",
    "hook": "Use reputation and conduct to decide whether the Red Knight aids or challenges the player.",
    "baseCost": 111.6,
    "baseProd": 0.765,
    "rating": 172
  },
  {
    "id": "the-m-e-g",
    "name": "The M.E.G.",
    "desc": "Friendly exploration faction with regiments, divisions, outposts, and discovery work.",
    "hook": "Progress from volunteer expeditions into specialized regiments and outpost command.",
    "baseCost": 691.92,
    "baseProd": 3.9015,
    "rating": 169
  },
  {
    "id": "entity-106",
    "name": "Entity 106 - 'tgochi.exe'",
    "desc": "Sentient software companion found on USB keys that possesses electronics and changes over time.",
    "hook": "Develop a digital pet through care, device possession, and conditional buffs or debuffs.",
    "baseCost": 4289.9,
    "baseProd": 19.8976,
    "rating": 90
  },
  {
    "id": "backrooms-remodeling-co",
    "name": "Backrooms Remodeling Co",
    "desc": "Militarized builders whose improvements catastrophically alter levels.",
    "hook": "Let remodeling operations split familiar zones into dangerous altered sublayers.",
    "baseCost": 26597.4,
    "baseProd": 101.478,
    "rating": 87
  },
  {
    "id": "entity-29",
    "name": "Entity 29 - \u201cBlub Cats\u201d",
    "desc": "Tameable telepathic pet family with pack behavior and unusual consumable tolerance.",
    "hook": "Offer variant pets whose pack traits and consumable reactions support different builds.",
    "baseCost": 164904,
    "baseProd": 517.538,
    "rating": 87
  },
  {
    "id": "a-river",
    "name": "A. River",
    "desc": "Missing archivist and infrastructure expert altered by Level 404.",
    "hook": "Trace database corruption and lost infrastructure to locate a transformed archivist.",
    "baseCost": 1022400,
    "baseProd": 2639.44,
    "rating": 86
  },
  {
    "id": "the-eyes-of-argos",
    "name": "The Eyes Of Argos",
    "desc": "Justice faction suited to crime, trials, patrol branches, and bounty systems.",
    "hook": "Track crimes and restitution through wanted levels, trials, patrols, and bounties.",
    "baseCost": 6338910,
    "baseProd": 13461.2,
    "rating": 83
  },
  {
    "id": "the-masked-maidens",
    "name": "Welcome to the Masked Maidens Database.",
    "desc": "Mask-powered infiltrator cells fighting corruption through disguise and espionage.",
    "hook": "Use masks and identities to infiltrate hostile sectors and expose corruption.",
    "baseCost": 39301200,
    "baseProd": 68651.9,
    "rating": 82
  },
  {
    "id": "the-lost",
    "name": "The Lost",
    "desc": "Ancient allied cultures offering relic gear, historical lore, and collective defense.",
    "hook": "Earn access to tribal relics by recovering history and defending old settlements.",
    "baseCost": 243668000,
    "baseProd": 350125,
    "rating": 80
  },
  {
    "id": "the-pantheon",
    "name": "The Pantheon",
    "desc": "Endgame cosmology connecting major unique entities as gods.",
    "hook": "Tie boons, curses, temples, and raid arcs to competing divine allegiances.",
    "baseCost": 1510740000,
    "baseProd": 1785640,
    "rating": 76
  },
  {
    "id": "the-u-e-c",
    "name": "The U.E.C.",
    "desc": "Paramilitary coalition with squads, colonies, technology, and ideological conflict.",
    "hook": "Stage competing exploration campaigns and technology races against the M.E.G.",
    "baseCost": 9366580000,
    "baseProd": 9106750,
    "rating": 75
  },
  {
    "id": "lines-please",
    "name": "Notable Person - The Actor",
    "desc": "Recurring stranger associated with plant growth, repeated deaths, and improvised weapons.",
    "hook": "Reintroduce the Actor after apparent deaths with changing motives and combat styles.",
    "baseCost": 58072800000,
    "baseProd": 46444400,
    "rating": 71
  },
  {
    "id": "the-black-knights",
    "name": "The Black Knights",
    "desc": "Non-human tactical units with exotic armor that become lethal when obstructed.",
    "hook": "Let players avoid, cooperate with, or provoke dangerous units for rare salvage.",
    "baseCost": 360051000000,
    "baseProd": 236866000,
    "rating": 59
  },
  {
    "id": "followers-of-jerry",
    "name": "Followers of Jerry",
    "desc": "Indoctrinating cult centered on Jerry, sanctuaries, doctrine, and recruitment.",
    "hook": "Use contact and recruitment pressure to turn neutral settlements into cult territory.",
    "baseCost": 2232320000000,
    "baseProd": 1208020000,
    "rating": 56
  },
  {
    "id": "tom-von-haderach",
    "name": "Tom Von Haderach",
    "desc": "Blanche's planar courier and recurring retrieval or delivery quest giver.",
    "hook": "Connect distant factions through book retrieval, rare-object delivery, and messages.",
    "baseCost": 13840400000000,
    "baseProd": 6160900000,
    "rating": 54
  },
  {
    "id": "eden-g",
    "name": "Eden G",
    "desc": "Missing entity expert who communicated peacefully and returned transformed from Heaven.",
    "hook": "Build a rescue arc around peaceful entity contact and uncertain transformation.",
    "baseCost": 85810300000000,
    "baseProd": 31420600000,
    "rating": 53
  },
  {
    "id": "the-b-n-t-g",
    "name": "The B.N.T.G.",
    "desc": "Merchant faction controlling trade, manufacturing, agriculture, stockpiles, and services.",
    "hook": "Make regional prices and crafting access respond to B.N.T.G. supply lines and diplomacy.",
    "baseCost": 532024000000000,
    "baseProd": 160245000000,
    "rating": 50
  },
  {
    "id": "kimiko",
    "name": "Kimiko",
    "desc": "Shapeshifting infiltrator with blue-fire orbs and flame walls.",
    "hook": "Mix disguise detection with blue-fire zoning in an infiltrator encounter.",
    "baseCost": 3298550000000000,
    "baseProd": 817249000000,
    "rating": 50
  },
  {
    "id": "entity-9",
    "name": "Entity 9 - 'Facelings'",
    "desc": "Neutral faceless population with adult, child, emotional, evolved, shadow, and mimic variants.",
    "hook": "Use silhouette and behavior rather than faces to distinguish traders, civilians, and threats.",
    "baseCost": 20451000000000000,
    "baseProd": 4167970000000,
    "rating": 46
  },
  {
    "id": "janus",
    "name": "Janus",
    "desc": "Doorway traveler whose eyes reveal possible futures and the past.",
    "hook": "Trade future telegraphs and past reconstruction against branching-choice consequences.",
    "baseCost": 126796000000000000,
    "baseProd": 21256600000000,
    "rating": 44
  },
  {
    "id": "the-augur",
    "name": "The Augur",
    "desc": "Traveling prophet whose accurate knowledge carries a non-monetary cost.",
    "hook": "Offer reliable predictions that impose narrative, reputation, or memory costs.",
    "baseCost": 786137000000000000,
    "baseProd": 108409000000000,
    "rating": 34
  },
  {
    "id": "herne-the-huntmaster",
    "name": "Herne The Huntmaster",
    "desc": "Primordial Wild Hunt master who accepts offerings and grants travel or longevity.",
    "hook": "Use player-made offerings to unlock hunts, travel routes, or extended-life boons.",
    "baseCost": 4874050000000000000,
    "baseProd": 552885000000000,
    "rating": 33
  }
];

export const GEAR: Gear[] = [
  {
    "id": "gear-l0-r0-weapon",
    "name": "Hallway Compass",
    "desc": "Recovered from Level 0 - 'Threshold'.",
    "hook": "Found only at Depth 0.",
    "slot": "Weapon",
    "rarity": "common",
    "cost": 50,
    "stats": { "clickMult": 1.04, "prodMult": 1.01, "luck": 0.004, "crit": 0.014 },
    "rating": 10,
    "levelIndex": 0,
  },
  {
    "id": "gear-l0-r1-light",
    "name": "Pipe Fragment",
    "desc": "Recovered from Level 0 - 'Threshold'.",
    "hook": "Found only at Depth 0.",
    "slot": "Light",
    "rarity": "uncommon",
    "cost": 75,
    "stats": { "clickMult": 1.02, "prodMult": 1.06, "luck": 0.022, "crit": 0.004 },
    "rating": 20,
    "levelIndex": 0,
  },
  {
    "id": "gear-l0-r2-armor",
    "name": "Threshold Shard",
    "desc": "Recovered from Level 0 - 'Threshold'.",
    "hook": "Found only at Depth 0.",
    "slot": "Armor",
    "rarity": "rare",
    "cost": 100,
    "stats": { "clickMult": 1.04, "prodMult": 1.04, "luck": 0.012, "crit": 0.009 },
    "rating": 30,
    "levelIndex": 0,
  },
  {
    "id": "gear-l0-r3-trinket",
    "name": "Wallpaper Scrap",
    "desc": "Recovered from Level 0 - 'Threshold'.",
    "hook": "Found only at Depth 0.",
    "slot": "Trinket",
    "rarity": "epic",
    "cost": 125,
    "stats": { "clickMult": 1.04, "prodMult": 1.04, "luck": 0.043, "crit": 0.018 },
    "rating": 40,
    "levelIndex": 0,
  },
  {
    "id": "gear-l0-r4-weapon",
    "name": "Passage Stone",
    "desc": "Recovered from Level 0 - 'Threshold'.",
    "hook": "Found only at Depth 0.",
    "slot": "Weapon",
    "rarity": "legendary",
    "cost": 150,
    "stats": { "clickMult": 1.1, "prodMult": 1.03, "luck": 0.01, "crit": 0.033 },
    "rating": 50,
    "levelIndex": 0,
  },
  {
    "id": "gear-l1-r0-light",
    "name": "Mailbox Latch",
    "desc": "Recovered from Level 1 - 'Habitable Zone'.",
    "hook": "Found only at Depth 1.",
    "slot": "Light",
    "rarity": "common",
    "cost": 150,
    "stats": { "clickMult": 1.03, "prodMult": 1.08, "luck": 0.031, "crit": 0.006 },
    "rating": 20,
    "levelIndex": 1,
  },
  {
    "id": "gear-l1-r1-armor",
    "name": "Porch Lantern",
    "desc": "Recovered from Level 1 - 'Habitable Zone'.",
    "hook": "Found only at Depth 1.",
    "slot": "Armor",
    "rarity": "uncommon",
    "cost": 225,
    "stats": { "clickMult": 1.05, "prodMult": 1.05, "luck": 0.016, "crit": 0.013 },
    "rating": 40,
    "levelIndex": 1,
  },
  {
    "id": "gear-l1-r2-trinket",
    "name": "Sidewalk Charm",
    "desc": "Recovered from Level 1 - 'Habitable Zone'.",
    "hook": "Found only at Depth 1.",
    "slot": "Trinket",
    "rarity": "rare",
    "cost": 300,
    "stats": { "clickMult": 1.06, "prodMult": 1.06, "luck": 0.06, "crit": 0.026 },
    "rating": 60,
    "levelIndex": 1,
  },
  {
    "id": "gear-l1-r3-weapon",
    "name": "Picket Stake",
    "desc": "Recovered from Level 1 - 'Habitable Zone'.",
    "hook": "Found only at Depth 1.",
    "slot": "Weapon",
    "rarity": "epic",
    "cost": 375,
    "stats": { "clickMult": 1.15, "prodMult": 1.05, "luck": 0.015, "crit": 0.047 },
    "rating": 80,
    "levelIndex": 1,
  },
  {
    "id": "gear-l1-r4-light",
    "name": "Driveway Marker",
    "desc": "Recovered from Level 1 - 'Habitable Zone'.",
    "hook": "Found only at Depth 1.",
    "slot": "Light",
    "rarity": "legendary",
    "cost": 450,
    "stats": { "clickMult": 1.06, "prodMult": 1.18, "luck": 0.072, "crit": 0.014 },
    "rating": 100,
    "levelIndex": 1,
  },
  {
    "id": "gear-l2-r0-armor",
    "name": "Desk Lamp Core",
    "desc": "Recovered from Level 4 - 'Abandoned Office'.",
    "hook": "Found only at Depth 2.",
    "slot": "Armor",
    "rarity": "common",
    "cost": 450,
    "stats": { "clickMult": 1.06, "prodMult": 1.06, "luck": 0.018, "crit": 0.015 },
    "rating": 30,
    "levelIndex": 2,
  },
  {
    "id": "gear-l2-r1-trinket",
    "name": "Printer Toner",
    "desc": "Recovered from Level 4 - 'Abandoned Office'.",
    "hook": "Found only at Depth 2.",
    "slot": "Trinket",
    "rarity": "uncommon",
    "cost": 675,
    "stats": { "clickMult": 1.06, "prodMult": 1.06, "luck": 0.069, "crit": 0.03 },
    "rating": 60,
    "levelIndex": 2,
  },
  {
    "id": "gear-l2-r2-weapon",
    "name": "Cabinet Plate",
    "desc": "Recovered from Level 4 - 'Abandoned Office'.",
    "hook": "Found only at Depth 2.",
    "slot": "Weapon",
    "rarity": "rare",
    "cost": 900,
    "stats": { "clickMult": 1.17, "prodMult": 1.06, "luck": 0.017, "crit": 0.055 },
    "rating": 90,
    "levelIndex": 2,
  },
  {
    "id": "gear-l2-r3-light",
    "name": "Monitor Shard",
    "desc": "Recovered from Level 4 - 'Abandoned Office'.",
    "hook": "Found only at Depth 2.",
    "slot": "Light",
    "rarity": "epic",
    "cost": 1125,
    "stats": { "clickMult": 1.07, "prodMult": 1.21, "luck": 0.084, "crit": 0.017 },
    "rating": 120,
    "levelIndex": 2,
  },
  {
    "id": "gear-l2-r4-armor",
    "name": "Keyboard Blade",
    "desc": "Recovered from Level 4 - 'Abandoned Office'.",
    "hook": "Found only at Depth 2.",
    "slot": "Armor",
    "rarity": "legendary",
    "cost": 1350,
    "stats": { "clickMult": 1.14, "prodMult": 1.14, "luck": 0.043, "crit": 0.034 },
    "rating": 150,
    "levelIndex": 2,
  },
  {
    "id": "gear-l3-r0-trinket",
    "name": "Room Key",
    "desc": "Recovered from Level 5 - 'Terror Hotel'.",
    "hook": "Found only at Depth 3.",
    "slot": "Trinket",
    "rarity": "common",
    "cost": 1350,
    "stats": { "clickMult": 1.07, "prodMult": 1.07, "luck": 0.072, "crit": 0.031 },
    "rating": 40,
    "levelIndex": 3,
  },
  {
    "id": "gear-l3-r1-weapon",
    "name": "Keycard Blade",
    "desc": "Recovered from Level 5 - 'Terror Hotel'.",
    "hook": "Found only at Depth 3.",
    "slot": "Weapon",
    "rarity": "uncommon",
    "cost": 2025,
    "stats": { "clickMult": 1.18, "prodMult": 1.06, "luck": 0.018, "crit": 0.058 },
    "rating": 80,
    "levelIndex": 3,
  },
  {
    "id": "gear-l3-r2-light",
    "name": "Bell Hammer",
    "desc": "Recovered from Level 5 - 'Terror Hotel'.",
    "hook": "Found only at Depth 3.",
    "slot": "Light",
    "rarity": "rare",
    "cost": 2700,
    "stats": { "clickMult": 1.07, "prodMult": 1.22, "luck": 0.089, "crit": 0.018 },
    "rating": 120,
    "levelIndex": 3,
  },
  {
    "id": "gear-l3-r3-armor",
    "name": "Chandelier Shard",
    "desc": "Recovered from Level 5 - 'Terror Hotel'.",
    "hook": "Found only at Depth 3.",
    "slot": "Armor",
    "rarity": "epic",
    "cost": 3375,
    "stats": { "clickMult": 1.15, "prodMult": 1.15, "luck": 0.046, "crit": 0.036 },
    "rating": 160,
    "levelIndex": 3,
  },
  {
    "id": "gear-l3-r4-trinket",
    "name": "Bedpost Club",
    "desc": "Recovered from Level 5 - 'Terror Hotel'.",
    "hook": "Found only at Depth 3.",
    "slot": "Trinket",
    "rarity": "legendary",
    "cost": 4050,
    "stats": { "clickMult": 1.15, "prodMult": 1.15, "luck": 0.166, "crit": 0.071 },
    "rating": 200,
    "levelIndex": 3,
  },
  {
    "id": "gear-l4-r0-weapon",
    "name": "Void Fragment",
    "desc": "Recovered from Level 6 - 'Lights Out'.",
    "hook": "Found only at Depth 4.",
    "slot": "Weapon",
    "rarity": "common",
    "cost": 4050,
    "stats": { "clickMult": 1.18, "prodMult": 1.06, "luck": 0.018, "crit": 0.057 },
    "rating": 50,
    "levelIndex": 4,
  },
  {
    "id": "gear-l4-r1-light",
    "name": "Gloom Lantern",
    "desc": "Recovered from Level 6 - 'Lights Out'.",
    "hook": "Found only at Depth 4.",
    "slot": "Light",
    "rarity": "uncommon",
    "cost": 6075,
    "stats": { "clickMult": 1.07, "prodMult": 1.22, "luck": 0.088, "crit": 0.018 },
    "rating": 100,
    "levelIndex": 4,
  },
  {
    "id": "gear-l4-r2-armor",
    "name": "Dusk Crystal",
    "desc": "Recovered from Level 6 - 'Lights Out'.",
    "hook": "Found only at Depth 4.",
    "slot": "Armor",
    "rarity": "rare",
    "cost": 8100,
    "stats": { "clickMult": 1.15, "prodMult": 1.15, "luck": 0.046, "crit": 0.037 },
    "rating": 150,
    "levelIndex": 4,
  },
  {
    "id": "gear-l4-r3-trinket",
    "name": "Shadow Cloak",
    "desc": "Recovered from Level 6 - 'Lights Out'.",
    "hook": "Found only at Depth 4.",
    "slot": "Trinket",
    "rarity": "epic",
    "cost": 10125,
    "stats": { "clickMult": 1.16, "prodMult": 1.16, "luck": 0.168, "crit": 0.072 },
    "rating": 200,
    "levelIndex": 4,
  },
  {
    "id": "gear-l4-r4-weapon",
    "name": "Whisper Charm",
    "desc": "Recovered from Level 6 - 'Lights Out'.",
    "hook": "Found only at Depth 4.",
    "slot": "Weapon",
    "rarity": "legendary",
    "cost": 12150,
    "stats": { "clickMult": 1.41, "prodMult": 1.14, "luck": 0.041, "crit": 0.13 },
    "rating": 250,
    "levelIndex": 4,
  },
  {
    "id": "gear-l5-r0-light",
    "name": "Tide Pearl",
    "desc": "Recovered from Level 7 - 'Thalassophobia'.",
    "hook": "Found only at Depth 5.",
    "slot": "Light",
    "rarity": "common",
    "cost": 12150,
    "stats": { "clickMult": 1.07, "prodMult": 1.21, "luck": 0.084, "crit": 0.017 },
    "rating": 60,
    "levelIndex": 5,
  },
  {
    "id": "gear-l5-r1-armor",
    "name": "Depth Stone",
    "desc": "Recovered from Level 7 - 'Thalassophobia'.",
    "hook": "Found only at Depth 5.",
    "slot": "Armor",
    "rarity": "uncommon",
    "cost": 18225,
    "stats": { "clickMult": 1.14, "prodMult": 1.14, "luck": 0.044, "crit": 0.035 },
    "rating": 120,
    "levelIndex": 5,
  },
  {
    "id": "gear-l5-r2-trinket",
    "name": "Wave Crest",
    "desc": "Recovered from Level 7 - 'Thalassophobia'.",
    "hook": "Found only at Depth 5.",
    "slot": "Trinket",
    "rarity": "rare",
    "cost": 24300,
    "stats": { "clickMult": 1.15, "prodMult": 1.15, "luck": 0.163, "crit": 0.069 },
    "rating": 180,
    "levelIndex": 5,
  },
  {
    "id": "gear-l5-r3-weapon",
    "name": "Buoy Lantern",
    "desc": "Recovered from Level 7 - 'Thalassophobia'.",
    "hook": "Found only at Depth 5.",
    "slot": "Weapon",
    "rarity": "epic",
    "cost": 30375,
    "stats": { "clickMult": 1.4, "prodMult": 1.13, "luck": 0.04, "crit": 0.128 },
    "rating": 240,
    "levelIndex": 5,
  },
  {
    "id": "gear-l5-r4-light",
    "name": "Abyss Pearl",
    "desc": "Recovered from Level 7 - 'Thalassophobia'.",
    "hook": "Found only at Depth 5.",
    "slot": "Light",
    "rarity": "legendary",
    "cost": 36450,
    "stats": { "clickMult": 1.16, "prodMult": 1.48, "luck": 0.193, "crit": 0.039 },
    "rating": 300,
    "levelIndex": 5,
  },
  {
    "id": "gear-l6-r0-armor",
    "name": "Pickaxe Head",
    "desc": "Recovered from Level 8 - 'Cave Systems'.",
    "hook": "Found only at Depth 6.",
    "slot": "Armor",
    "rarity": "common",
    "cost": 36450,
    "stats": { "clickMult": 1.13, "prodMult": 1.13, "luck": 0.041, "crit": 0.032 },
    "rating": 70,
    "levelIndex": 6,
  },
  {
    "id": "gear-l6-r1-trinket",
    "name": "Boulder Charm",
    "desc": "Recovered from Level 8 - 'Cave Systems'.",
    "hook": "Found only at Depth 6.",
    "slot": "Trinket",
    "rarity": "uncommon",
    "cost": 54675,
    "stats": { "clickMult": 1.14, "prodMult": 1.14, "luck": 0.152, "crit": 0.065 },
    "rating": 140,
    "levelIndex": 6,
  },
  {
    "id": "gear-l6-r2-weapon",
    "name": "Crystal Shard",
    "desc": "Recovered from Level 8 - 'Cave Systems'.",
    "hook": "Found only at Depth 6.",
    "slot": "Weapon",
    "rarity": "rare",
    "cost": 72900,
    "stats": { "clickMult": 1.38, "prodMult": 1.13, "luck": 0.038, "crit": 0.121 },
    "rating": 210,
    "levelIndex": 6,
  },
  {
    "id": "gear-l6-r3-light",
    "name": "Ore Fragment",
    "desc": "Recovered from Level 8 - 'Cave Systems'.",
    "hook": "Found only at Depth 6.",
    "slot": "Light",
    "rarity": "epic",
    "cost": 91125,
    "stats": { "clickMult": 1.15, "prodMult": 1.46, "luck": 0.185, "crit": 0.037 },
    "rating": 280,
    "levelIndex": 6,
  },
  {
    "id": "gear-l6-r4-armor",
    "name": "Fungus Lantern",
    "desc": "Recovered from Level 8 - 'Cave Systems'.",
    "hook": "Found only at Depth 6.",
    "slot": "Armor",
    "rarity": "legendary",
    "cost": 109350,
    "stats": { "clickMult": 1.3, "prodMult": 1.3, "luck": 0.093, "crit": 0.075 },
    "rating": 350,
    "levelIndex": 6,
  },
  {
    "id": "gear-l7-r0-trinket",
    "name": "Driveway Marker",
    "desc": "Recovered from Level 9 - 'The Suburbs'.",
    "hook": "Found only at Depth 7.",
    "slot": "Trinket",
    "rarity": "common",
    "cost": 109350,
    "stats": { "clickMult": 1.13, "prodMult": 1.13, "luck": 0.138, "crit": 0.059 },
    "rating": 80,
    "levelIndex": 7,
  },
  {
    "id": "gear-l7-r1-weapon",
    "name": "Porch Lantern",
    "desc": "Recovered from Level 9 - 'The Suburbs'.",
    "hook": "Found only at Depth 7.",
    "slot": "Weapon",
    "rarity": "uncommon",
    "cost": 164025,
    "stats": { "clickMult": 1.34, "prodMult": 1.11, "luck": 0.034, "crit": 0.11 },
    "rating": 160,
    "levelIndex": 7,
  },
  {
    "id": "gear-l7-r2-light",
    "name": "Window Shard",
    "desc": "Recovered from Level 9 - 'The Suburbs'.",
    "hook": "Found only at Depth 7.",
    "slot": "Light",
    "rarity": "rare",
    "cost": 218700,
    "stats": { "clickMult": 1.14, "prodMult": 1.43, "luck": 0.171, "crit": 0.034 },
    "rating": 240,
    "levelIndex": 7,
  },
  {
    "id": "gear-l7-r3-armor",
    "name": "Lawn Key",
    "desc": "Recovered from Level 9 - 'The Suburbs'.",
    "hook": "Found only at Depth 7.",
    "slot": "Armor",
    "rarity": "epic",
    "cost": 273375,
    "stats": { "clickMult": 1.28, "prodMult": 1.28, "luck": 0.087, "crit": 0.07 },
    "rating": 320,
    "levelIndex": 7,
  },
  {
    "id": "gear-l7-r4-trinket",
    "name": "Picket Stake",
    "desc": "Recovered from Level 9 - 'The Suburbs'.",
    "hook": "Found only at Depth 7.",
    "slot": "Trinket",
    "rarity": "legendary",
    "cost": 328050,
    "stats": { "clickMult": 1.3, "prodMult": 1.3, "luck": 0.317, "crit": 0.135 },
    "rating": 400,
    "levelIndex": 7,
  },
  {
    "id": "gear-l8-r0-weapon",
    "name": "Plowshare",
    "desc": "Recovered from Level 10 - 'Bumper Crop'.",
    "hook": "Found only at Depth 8.",
    "slot": "Weapon",
    "rarity": "common",
    "cost": 328050,
    "stats": { "clickMult": 1.31, "prodMult": 1.1, "luck": 0.031, "crit": 0.099 },
    "rating": 90,
    "levelIndex": 8,
  },
  {
    "id": "gear-l8-r1-light",
    "name": "Scarecrow Talisman",
    "desc": "Recovered from Level 10 - 'Bumper Crop'.",
    "hook": "Found only at Depth 8.",
    "slot": "Light",
    "rarity": "uncommon",
    "cost": 492075,
    "stats": { "clickMult": 1.13, "prodMult": 1.39, "luck": 0.154, "crit": 0.031 },
    "rating": 180,
    "levelIndex": 8,
  },
  {
    "id": "gear-l8-r2-armor",
    "name": "Harvest Blade",
    "desc": "Recovered from Level 10 - 'Bumper Crop'.",
    "hook": "Found only at Depth 8.",
    "slot": "Armor",
    "rarity": "rare",
    "cost": 656100,
    "stats": { "clickMult": 1.26, "prodMult": 1.26, "luck": 0.08, "crit": 0.064 },
    "rating": 270,
    "levelIndex": 8,
  },
  {
    "id": "gear-l8-r3-trinket",
    "name": "Breeze Stone",
    "desc": "Recovered from Level 10 - 'Bumper Crop'.",
    "hook": "Found only at Depth 8.",
    "slot": "Trinket",
    "rarity": "epic",
    "cost": 820125,
    "stats": { "clickMult": 1.27, "prodMult": 1.27, "luck": 0.294, "crit": 0.125 },
    "rating": 360,
    "levelIndex": 8,
  },
  {
    "id": "gear-l8-r4-weapon",
    "name": "Wheat Stalk Charm",
    "desc": "Recovered from Level 10 - 'Bumper Crop'.",
    "hook": "Found only at Depth 8.",
    "slot": "Weapon",
    "rarity": "legendary",
    "cost": 984150,
    "stats": { "clickMult": 1.71, "prodMult": 1.24, "luck": 0.071, "crit": 0.227 },
    "rating": 450,
    "levelIndex": 8,
  },
  {
    "id": "gear-l9-r0-light",
    "name": "Pixel Shard",
    "desc": "Recovered from Level 12 - 'Matrix'.",
    "hook": "Found only at Depth 9.",
    "slot": "Light",
    "rarity": "common",
    "cost": 984150,
    "stats": { "clickMult": 1.11, "prodMult": 1.34, "luck": 0.137, "crit": 0.027 },
    "rating": 100,
    "levelIndex": 9,
  },
  {
    "id": "gear-l9-r1-armor",
    "name": "Firewall Plate",
    "desc": "Recovered from Level 12 - 'Matrix'.",
    "hook": "Found only at Depth 9.",
    "slot": "Armor",
    "rarity": "uncommon",
    "cost": 1476225,
    "stats": { "clickMult": 1.23, "prodMult": 1.23, "luck": 0.071, "crit": 0.057 },
    "rating": 200,
    "levelIndex": 9,
  },
  {
    "id": "gear-l9-r2-trinket",
    "name": "Glitch Fragment",
    "desc": "Recovered from Level 12 - 'Matrix'.",
    "hook": "Found only at Depth 9.",
    "slot": "Trinket",
    "rarity": "rare",
    "cost": 1968300,
    "stats": { "clickMult": 1.25, "prodMult": 1.25, "luck": 0.265, "crit": 0.113 },
    "rating": 300,
    "levelIndex": 9,
  },
  {
    "id": "gear-l9-r3-weapon",
    "name": "Matrix Core",
    "desc": "Recovered from Level 12 - 'Matrix'.",
    "hook": "Found only at Depth 9.",
    "slot": "Weapon",
    "rarity": "epic",
    "cost": 2460375,
    "stats": { "clickMult": 1.65, "prodMult": 1.22, "luck": 0.065, "crit": 0.208 },
    "rating": 400,
    "levelIndex": 9,
  },
  {
    "id": "gear-l9-r4-light",
    "name": "Code Blade",
    "desc": "Recovered from Level 12 - 'Matrix'.",
    "hook": "Found only at Depth 9.",
    "slot": "Light",
    "rarity": "legendary",
    "cost": 2952450,
    "stats": { "clickMult": 1.26, "prodMult": 1.79, "luck": 0.315, "crit": 0.063 },
    "rating": 500,
    "levelIndex": 9,
  },
  {
    "id": "gear-l10-r0-armor",
    "name": "Fence Post Club",
    "desc": "Recovered from Level 14 - 'Paradise'.",
    "hook": "Found only at Depth 10.",
    "slot": "Armor",
    "rarity": "common",
    "cost": 2952450,
    "stats": { "clickMult": 1.2, "prodMult": 1.2, "luck": 0.062, "crit": 0.05 },
    "rating": 110,
    "levelIndex": 10,
  },
  {
    "id": "gear-l10-r1-trinket",
    "name": "Plowshare",
    "desc": "Recovered from Level 14 - 'Paradise'.",
    "hook": "Found only at Depth 10.",
    "slot": "Trinket",
    "rarity": "uncommon",
    "cost": 4428675,
    "stats": { "clickMult": 1.22, "prodMult": 1.22, "luck": 0.234, "crit": 0.1 },
    "rating": 220,
    "levelIndex": 10,
  },
  {
    "id": "gear-l10-r2-weapon",
    "name": "Breeze Stone",
    "desc": "Recovered from Level 14 - 'Paradise'.",
    "hook": "Found only at Depth 10.",
    "slot": "Weapon",
    "rarity": "rare",
    "cost": 5904900,
    "stats": { "clickMult": 1.58, "prodMult": 1.19, "luck": 0.058, "crit": 0.186 },
    "rating": 330,
    "levelIndex": 10,
  },
  {
    "id": "gear-l10-r3-light",
    "name": "Wheat Stalk Charm",
    "desc": "Recovered from Level 14 - 'Paradise'.",
    "hook": "Found only at Depth 10.",
    "slot": "Light",
    "rarity": "epic",
    "cost": 7381125,
    "stats": { "clickMult": 1.24, "prodMult": 1.71, "luck": 0.285, "crit": 0.057 },
    "rating": 440,
    "levelIndex": 10,
  },
  {
    "id": "gear-l10-r4-armor",
    "name": "Harvest Blade",
    "desc": "Recovered from Level 14 - 'Paradise'.",
    "hook": "Found only at Depth 10.",
    "slot": "Armor",
    "rarity": "legendary",
    "cost": 8857350,
    "stats": { "clickMult": 1.46, "prodMult": 1.46, "luck": 0.144, "crit": 0.115 },
    "rating": 550,
    "levelIndex": 10,
  },
  {
    "id": "gear-l11-r0-trinket",
    "name": "Tablet Shard",
    "desc": "Recovered from Level 22 - 'Ruins Left Behind'.",
    "hook": "Found only at Depth 11.",
    "slot": "Trinket",
    "rarity": "common",
    "cost": 8857350,
    "stats": { "clickMult": 1.19, "prodMult": 1.19, "luck": 0.204, "crit": 0.087 },
    "rating": 120,
    "levelIndex": 11,
  },
  {
    "id": "gear-l11-r1-weapon",
    "name": "Relic Fragment",
    "desc": "Recovered from Level 22 - 'Ruins Left Behind'.",
    "hook": "Found only at Depth 11.",
    "slot": "Weapon",
    "rarity": "uncommon",
    "cost": 13286025,
    "stats": { "clickMult": 1.51, "prodMult": 1.17, "luck": 0.051, "crit": 0.163 },
    "rating": 240,
    "levelIndex": 11,
  },
  {
    "id": "gear-l11-r2-light",
    "name": "Fresco Scrap",
    "desc": "Recovered from Level 22 - 'Ruins Left Behind'.",
    "hook": "Found only at Depth 11.",
    "slot": "Light",
    "rarity": "rare",
    "cost": 17714700,
    "stats": { "clickMult": 1.21, "prodMult": 1.63, "luck": 0.253, "crit": 0.051 },
    "rating": 360,
    "levelIndex": 11,
  },
  {
    "id": "gear-l11-r3-armor",
    "name": "Rubble Stone",
    "desc": "Recovered from Level 22 - 'Ruins Left Behind'.",
    "hook": "Found only at Depth 11.",
    "slot": "Armor",
    "rarity": "epic",
    "cost": 22143375,
    "stats": { "clickMult": 1.41, "prodMult": 1.41, "luck": 0.129, "crit": 0.103 },
    "rating": 480,
    "levelIndex": 11,
  },
  {
    "id": "gear-l11-r4-trinket",
    "name": "Column Chip",
    "desc": "Recovered from Level 22 - 'Ruins Left Behind'.",
    "hook": "Found only at Depth 11.",
    "slot": "Trinket",
    "rarity": "legendary",
    "cost": 26572050,
    "stats": { "clickMult": 1.44, "prodMult": 1.44, "luck": 0.469, "crit": 0.2 },
    "rating": 600,
    "levelIndex": 11,
  },
  {
    "id": "gear-l12-r0-weapon",
    "name": "Plowshare",
    "desc": "Recovered from Level 23 - 'The Petrified Garden'.",
    "hook": "Found only at Depth 12.",
    "slot": "Weapon",
    "rarity": "common",
    "cost": 26572050,
    "stats": { "clickMult": 1.44, "prodMult": 1.15, "luck": 0.044, "crit": 0.141 },
    "rating": 130,
    "levelIndex": 12,
  },
  {
    "id": "gear-l12-r1-light",
    "name": "Harvest Blade",
    "desc": "Recovered from Level 23 - 'The Petrified Garden'.",
    "hook": "Found only at Depth 12.",
    "slot": "Light",
    "rarity": "uncommon",
    "cost": 39858075,
    "stats": { "clickMult": 1.18, "prodMult": 1.55, "luck": 0.221, "crit": 0.044 },
    "rating": 260,
    "levelIndex": 12,
  },
  {
    "id": "gear-l12-r2-armor",
    "name": "Seed Pendant",
    "desc": "Recovered from Level 23 - 'The Petrified Garden'.",
    "hook": "Found only at Depth 12.",
    "slot": "Armor",
    "rarity": "rare",
    "cost": 53144100,
    "stats": { "clickMult": 1.36, "prodMult": 1.36, "luck": 0.114, "crit": 0.091 },
    "rating": 390,
    "levelIndex": 12,
  },
  {
    "id": "gear-l12-r3-trinket",
    "name": "Fence Post Club",
    "desc": "Recovered from Level 23 - 'The Petrified Garden'.",
    "hook": "Found only at Depth 12.",
    "slot": "Trinket",
    "rarity": "epic",
    "cost": 66430125,
    "stats": { "clickMult": 1.39, "prodMult": 1.39, "luck": 0.419, "crit": 0.179 },
    "rating": 520,
    "levelIndex": 12,
  },
  {
    "id": "gear-l12-r4-weapon",
    "name": "Wheat Stalk Charm",
    "desc": "Recovered from Level 23 - 'The Petrified Garden'.",
    "hook": "Found only at Depth 12.",
    "slot": "Weapon",
    "rarity": "legendary",
    "cost": 79716150,
    "stats": { "clickMult": 2.01, "prodMult": 1.34, "luck": 0.101, "crit": 0.325 },
    "rating": 650,
    "levelIndex": 12,
  },
  {
    "id": "gear-l13-r0-light",
    "name": "Pulse Core",
    "desc": "Recovered from Level 37 - 'Sublimity'.",
    "hook": "Found only at Depth 13.",
    "slot": "Light",
    "rarity": "common",
    "cost": 79716150,
    "stats": { "clickMult": 1.16, "prodMult": 1.47, "luck": 0.19, "crit": 0.038 },
    "rating": 140,
    "levelIndex": 13,
  },
  {
    "id": "gear-l13-r1-armor",
    "name": "Vacuum Charm",
    "desc": "Recovered from Level 37 - 'Sublimity'.",
    "hook": "Found only at Depth 13.",
    "slot": "Armor",
    "rarity": "uncommon",
    "cost": 119574225,
    "stats": { "clickMult": 1.32, "prodMult": 1.32, "luck": 0.099, "crit": 0.079 },
    "rating": 280,
    "levelIndex": 13,
  },
  {
    "id": "gear-l13-r2-trinket",
    "name": "Singularity Shard",
    "desc": "Recovered from Level 37 - 'Sublimity'.",
    "hook": "Found only at Depth 13.",
    "slot": "Trinket",
    "rarity": "rare",
    "cost": 159432300,
    "stats": { "clickMult": 1.34, "prodMult": 1.34, "luck": 0.367, "crit": 0.157 },
    "rating": 420,
    "levelIndex": 13,
  },
  {
    "id": "gear-l13-r3-weapon",
    "name": "Event Crystal",
    "desc": "Recovered from Level 37 - 'Sublimity'.",
    "hook": "Found only at Depth 13.",
    "slot": "Weapon",
    "rarity": "epic",
    "cost": 199290375,
    "stats": { "clickMult": 1.9, "prodMult": 1.3, "luck": 0.09, "crit": 0.288 },
    "rating": 560,
    "levelIndex": 13,
  },
  {
    "id": "gear-l13-r4-light",
    "name": "Zero Point",
    "desc": "Recovered from Level 37 - 'Sublimity'.",
    "hook": "Found only at Depth 13.",
    "slot": "Light",
    "rarity": "legendary",
    "cost": 239148450,
    "stats": { "clickMult": 1.36, "prodMult": 2.09, "luck": 0.436, "crit": 0.087 },
    "rating": 700,
    "levelIndex": 13,
  },
  {
    "id": "gear-l14-r0-armor",
    "name": "Ancient Seal",
    "desc": "Recovered from Level 69 - 'The Road Trip of Affliction'.",
    "hook": "Found only at Depth 14.",
    "slot": "Armor",
    "rarity": "common",
    "cost": 239148450,
    "stats": { "clickMult": 1.27, "prodMult": 1.27, "luck": 0.084, "crit": 0.068 },
    "rating": 150,
    "levelIndex": 14,
  },
  {
    "id": "gear-l14-r1-trinket",
    "name": "Rubble Stone",
    "desc": "Recovered from Level 69 - 'The Road Trip of Affliction'.",
    "hook": "Found only at Depth 14.",
    "slot": "Trinket",
    "rarity": "uncommon",
    "cost": 358722675,
    "stats": { "clickMult": 1.3, "prodMult": 1.3, "luck": 0.317, "crit": 0.135 },
    "rating": 300,
    "levelIndex": 14,
  },
  {
    "id": "gear-l14-r2-weapon",
    "name": "Relic Fragment",
    "desc": "Recovered from Level 69 - 'The Road Trip of Affliction'.",
    "hook": "Found only at Depth 14.",
    "slot": "Weapon",
    "rarity": "rare",
    "cost": 478296900,
    "stats": { "clickMult": 1.79, "prodMult": 1.26, "luck": 0.079, "crit": 0.251 },
    "rating": 450,
    "levelIndex": 14,
  },
  {
    "id": "gear-l14-r3-light",
    "name": "Tablet Shard",
    "desc": "Recovered from Level 69 - 'The Road Trip of Affliction'.",
    "hook": "Found only at Depth 14.",
    "slot": "Light",
    "rarity": "epic",
    "cost": 597871125,
    "stats": { "clickMult": 1.32, "prodMult": 1.96, "luck": 0.385, "crit": 0.077 },
    "rating": 600,
    "levelIndex": 14,
  },
  {
    "id": "gear-l14-r4-armor",
    "name": "Mosaic Piece",
    "desc": "Recovered from Level 69 - 'The Road Trip of Affliction'.",
    "hook": "Found only at Depth 14.",
    "slot": "Armor",
    "rarity": "legendary",
    "cost": 717445350,
    "stats": { "clickMult": 1.62, "prodMult": 1.62, "luck": 0.194, "crit": 0.155 },
    "rating": 750,
    "levelIndex": 14,
  },
  {
    "id": "gear-l15-r0-trinket",
    "name": "Lawn Key",
    "desc": "Recovered from Level 200 - 'Home'.",
    "hook": "Found only at Depth 15.",
    "slot": "Trinket",
    "rarity": "common",
    "cost": 717445350,
    "stats": { "clickMult": 1.25, "prodMult": 1.25, "luck": 0.27, "crit": 0.115 },
    "rating": 160,
    "levelIndex": 15,
  },
  {
    "id": "gear-l15-r1-weapon",
    "name": "Mailbox Latch",
    "desc": "Recovered from Level 200 - 'Home'.",
    "hook": "Found only at Depth 15.",
    "slot": "Weapon",
    "rarity": "uncommon",
    "cost": 1076168025,
    "stats": { "clickMult": 1.67, "prodMult": 1.23, "luck": 0.067, "crit": 0.216 },
    "rating": 320,
    "levelIndex": 15,
  },
  {
    "id": "gear-l15-r2-light",
    "name": "Picket Stake",
    "desc": "Recovered from Level 200 - 'Home'.",
    "hook": "Found only at Depth 15.",
    "slot": "Light",
    "rarity": "rare",
    "cost": 1434890700,
    "stats": { "clickMult": 1.28, "prodMult": 1.84, "luck": 0.335, "crit": 0.067 },
    "rating": 480,
    "levelIndex": 15,
  },
  {
    "id": "gear-l15-r3-armor",
    "name": "Porch Lantern",
    "desc": "Recovered from Level 200 - 'Home'.",
    "hook": "Found only at Depth 15.",
    "slot": "Armor",
    "rarity": "epic",
    "cost": 1793613375,
    "stats": { "clickMult": 1.55, "prodMult": 1.55, "luck": 0.171, "crit": 0.137 },
    "rating": 640,
    "levelIndex": 15,
  },
  {
    "id": "gear-l15-r4-trinket",
    "name": "Driveway Marker",
    "desc": "Recovered from Level 200 - 'Home'.",
    "hook": "Found only at Depth 15.",
    "slot": "Trinket",
    "rarity": "legendary",
    "cost": 2152336050,
    "stats": { "clickMult": 1.58, "prodMult": 1.58, "luck": 0.621, "crit": 0.265 },
    "rating": 800,
    "levelIndex": 15,
  },
  {
    "id": "gear-l16-r0-weapon",
    "name": "Code Blade",
    "desc": "Recovered from Level 263 - 'Untextured'.",
    "hook": "Found only at Depth 16.",
    "slot": "Weapon",
    "rarity": "common",
    "cost": 2152336050,
    "stats": { "clickMult": 1.57, "prodMult": 1.19, "luck": 0.057, "crit": 0.183 },
    "rating": 170,
    "levelIndex": 16,
  },
  {
    "id": "gear-l16-r1-light",
    "name": "Glitch Fragment",
    "desc": "Recovered from Level 263 - 'Untextured'.",
    "hook": "Found only at Depth 16.",
    "slot": "Light",
    "rarity": "uncommon",
    "cost": 3228504075,
    "stats": { "clickMult": 1.24, "prodMult": 1.72, "luck": 0.287, "crit": 0.057 },
    "rating": 340,
    "levelIndex": 16,
  },
  {
    "id": "gear-l16-r2-armor",
    "name": "Buffer Charm",
    "desc": "Recovered from Level 263 - 'Untextured'.",
    "hook": "Found only at Depth 16.",
    "slot": "Armor",
    "rarity": "rare",
    "cost": 4304672100,
    "stats": { "clickMult": 1.47, "prodMult": 1.47, "luck": 0.148, "crit": 0.118 },
    "rating": 510,
    "levelIndex": 16,
  },
  {
    "id": "gear-l16-r3-trinket",
    "name": "Matrix Core",
    "desc": "Recovered from Level 263 - 'Untextured'.",
    "hook": "Found only at Depth 16.",
    "slot": "Trinket",
    "rarity": "epic",
    "cost": 5380840125,
    "stats": { "clickMult": 1.51, "prodMult": 1.51, "luck": 0.544, "crit": 0.232 },
    "rating": 680,
    "levelIndex": 16,
  },
  {
    "id": "gear-l16-r4-weapon",
    "name": "Cache Crystal",
    "desc": "Recovered from Level 263 - 'Untextured'.",
    "hook": "Found only at Depth 16.",
    "slot": "Weapon",
    "rarity": "legendary",
    "cost": 6457008150,
    "stats": { "clickMult": 2.32, "prodMult": 1.44, "luck": 0.132, "crit": 0.422 },
    "rating": 850,
    "levelIndex": 16,
  },
  {
    "id": "gear-l17-r0-light",
    "name": "Buoy Lantern",
    "desc": "Recovered from Level 289 - 'Overflow'.",
    "hook": "Found only at Depth 17.",
    "slot": "Light",
    "rarity": "common",
    "cost": 6457008150,
    "stats": { "clickMult": 1.2, "prodMult": 1.61, "luck": 0.242, "crit": 0.048 },
    "rating": 180,
    "levelIndex": 17,
  },
  {
    "id": "gear-l17-r1-armor",
    "name": "Depth Stone",
    "desc": "Recovered from Level 289 - 'Overflow'.",
    "hook": "Found only at Depth 17.",
    "slot": "Armor",
    "rarity": "uncommon",
    "cost": 9685512225,
    "stats": { "clickMult": 1.4, "prodMult": 1.4, "luck": 0.126, "crit": 0.101 },
    "rating": 360,
    "levelIndex": 17,
  },
  {
    "id": "gear-l17-r2-trinket",
    "name": "Abyss Pearl",
    "desc": "Recovered from Level 289 - 'Overflow'.",
    "hook": "Found only at Depth 17.",
    "slot": "Trinket",
    "rarity": "rare",
    "cost": 12914016300,
    "stats": { "clickMult": 1.44, "prodMult": 1.44, "luck": 0.47, "crit": 0.2 },
    "rating": 540,
    "levelIndex": 17,
  },
  {
    "id": "gear-l17-r3-weapon",
    "name": "Ripple Charm",
    "desc": "Recovered from Level 289 - 'Overflow'.",
    "hook": "Found only at Depth 17.",
    "slot": "Weapon",
    "rarity": "epic",
    "cost": 16142520375,
    "stats": { "clickMult": 2.15, "prodMult": 1.38, "luck": 0.115, "crit": 0.368 },
    "rating": 720,
    "levelIndex": 17,
  },
  {
    "id": "gear-l17-r4-light",
    "name": "Current Blade",
    "desc": "Recovered from Level 289 - 'Overflow'.",
    "hook": "Found only at Depth 17.",
    "slot": "Light",
    "rarity": "legendary",
    "cost": 19371024450,
    "stats": { "clickMult": 1.46, "prodMult": 2.39, "luck": 0.558, "crit": 0.112 },
    "rating": 900,
    "levelIndex": 17,
  },
  {
    "id": "gear-l18-r0-armor",
    "name": "Glitch Fragment",
    "desc": "Recovered from level 404 - 'my dearly fragmented'.",
    "hook": "Found only at Depth 18.",
    "slot": "Armor",
    "rarity": "common",
    "cost": 19371024450,
    "stats": { "clickMult": 1.34, "prodMult": 1.34, "luck": 0.106, "crit": 0.085 },
    "rating": 190,
    "levelIndex": 18,
  },
  {
    "id": "gear-l18-r1-trinket",
    "name": "Cache Crystal",
    "desc": "Recovered from level 404 - 'my dearly fragmented'.",
    "hook": "Found only at Depth 18.",
    "slot": "Trinket",
    "rarity": "uncommon",
    "cost": 29056536675,
    "stats": { "clickMult": 1.37, "prodMult": 1.37, "luck": 0.399, "crit": 0.17 },
    "rating": 380,
    "levelIndex": 18,
  },
  {
    "id": "gear-l18-r2-weapon",
    "name": "Matrix Core",
    "desc": "Recovered from level 404 - 'my dearly fragmented'.",
    "hook": "Found only at Depth 18.",
    "slot": "Weapon",
    "rarity": "rare",
    "cost": 38742048900,
    "stats": { "clickMult": 1.99, "prodMult": 1.33, "luck": 0.099, "crit": 0.317 },
    "rating": 570,
    "levelIndex": 18,
  },
  {
    "id": "gear-l18-r3-light",
    "name": "Pixel Shard",
    "desc": "Recovered from level 404 - 'my dearly fragmented'.",
    "hook": "Found only at Depth 18.",
    "slot": "Light",
    "rarity": "epic",
    "cost": 48427561125,
    "stats": { "clickMult": 1.4, "prodMult": 2.21, "luck": 0.486, "crit": 0.097 },
    "rating": 760,
    "levelIndex": 18,
  },
  {
    "id": "gear-l18-r4-armor",
    "name": "Firewall Plate",
    "desc": "Recovered from level 404 - 'my dearly fragmented'.",
    "hook": "Found only at Depth 18.",
    "slot": "Armor",
    "rarity": "legendary",
    "cost": 58113073350,
    "stats": { "clickMult": 1.78, "prodMult": 1.78, "luck": 0.245, "crit": 0.196 },
    "rating": 950,
    "levelIndex": 18,
  },
  {
    "id": "gear-l19-r0-trinket",
    "name": "Null Fragment",
    "desc": "Recovered from Level 601 - 'The End'.",
    "hook": "Found only at Depth 19.",
    "slot": "Trinket",
    "rarity": "common",
    "cost": 58113073350,
    "stats": { "clickMult": 1.31, "prodMult": 1.31, "luck": 0.336, "crit": 0.143 },
    "rating": 200,
    "levelIndex": 19,
  },
  {
    "id": "gear-l19-r1-weapon",
    "name": "Zero Point",
    "desc": "Recovered from Level 601 - 'The End'.",
    "hook": "Found only at Depth 19.",
    "slot": "Weapon",
    "rarity": "uncommon",
    "cost": 87169610025,
    "stats": { "clickMult": 1.84, "prodMult": 1.28, "luck": 0.084, "crit": 0.269 },
    "rating": 400,
    "levelIndex": 19,
  },
  {
    "id": "gear-l19-r2-light",
    "name": "Singularity Shard",
    "desc": "Recovered from Level 601 - 'The End'.",
    "hook": "Found only at Depth 19.",
    "slot": "Light",
    "rarity": "rare",
    "cost": 116226146700,
    "stats": { "clickMult": 1.35, "prodMult": 2.04, "luck": 0.417, "crit": 0.083 },
    "rating": 600,
    "levelIndex": 19,
  },
  {
    "id": "gear-l19-r3-armor",
    "name": "Pulse Core",
    "desc": "Recovered from Level 601 - 'The End'.",
    "hook": "Found only at Depth 19.",
    "slot": "Armor",
    "rarity": "epic",
    "cost": 145282683375,
    "stats": { "clickMult": 1.68, "prodMult": 1.68, "luck": 0.213, "crit": 0.17 },
    "rating": 800,
    "levelIndex": 19,
  },
  {
    "id": "gear-l19-r4-trinket",
    "name": "Horizon Stone",
    "desc": "Recovered from Level 601 - 'The End'.",
    "hook": "Found only at Depth 19.",
    "slot": "Trinket",
    "rarity": "legendary",
    "cost": 174339220050,
    "stats": { "clickMult": 1.72, "prodMult": 1.72, "luck": 0.773, "crit": 0.33 },
    "rating": 1000,
    "levelIndex": 19,
  },
  {
    "id": "gear-l20-r0-weapon",
    "name": "Vacuum Charm",
    "desc": "Recovered from Level 906 - 'The Cygnus Archive'.",
    "hook": "Found only at Depth 20.",
    "slot": "Weapon",
    "rarity": "common",
    "cost": 174339220050,
    "stats": { "clickMult": 1.71, "prodMult": 1.23, "luck": 0.07, "crit": 0.226 },
    "rating": 210,
    "levelIndex": 20,
  },
  {
    "id": "gear-l20-r1-light",
    "name": "Null Fragment",
    "desc": "Recovered from Level 906 - 'The Cygnus Archive'.",
    "hook": "Found only at Depth 20.",
    "slot": "Light",
    "rarity": "uncommon",
    "cost": 261508830075,
    "stats": { "clickMult": 1.29, "prodMult": 1.88, "luck": 0.352, "crit": 0.07 },
    "rating": 420,
    "levelIndex": 20,
  },
  {
    "id": "gear-l20-r2-armor",
    "name": "Horizon Stone",
    "desc": "Recovered from Level 906 - 'The Cygnus Archive'.",
    "hook": "Found only at Depth 20.",
    "slot": "Armor",
    "rarity": "rare",
    "cost": 348678440100,
    "stats": { "clickMult": 1.58, "prodMult": 1.58, "luck": 0.182, "crit": 0.146 },
    "rating": 630,
    "levelIndex": 20,
  },
  {
    "id": "gear-l20-r3-trinket",
    "name": "Event Crystal",
    "desc": "Recovered from Level 906 - 'The Cygnus Archive'.",
    "hook": "Found only at Depth 20.",
    "slot": "Trinket",
    "rarity": "epic",
    "cost": 435848050125,
    "stats": { "clickMult": 1.63, "prodMult": 1.63, "luck": 0.67, "crit": 0.286 },
    "rating": 840,
    "levelIndex": 20,
  },
  {
    "id": "gear-l20-r4-weapon",
    "name": "Zero Point",
    "desc": "Recovered from Level 906 - 'The Cygnus Archive'.",
    "hook": "Found only at Depth 20.",
    "slot": "Weapon",
    "rarity": "legendary",
    "cost": 523017660150,
    "stats": { "clickMult": 2.62, "prodMult": 1.54, "luck": 0.162, "crit": 0.519 },
    "rating": 1050,
    "levelIndex": 20,
  },
  {
    "id": "gear-l21-r0-light",
    "name": "Null Fragment",
    "desc": "Recovered from Level 999.",
    "hook": "Found only at Depth 21.",
    "slot": "Light",
    "rarity": "common",
    "cost": 523017660150,
    "stats": { "clickMult": 1.25, "prodMult": 1.74, "luck": 0.295, "crit": 0.059 },
    "rating": 220,
    "levelIndex": 21,
  },
  {
    "id": "gear-l21-r1-armor",
    "name": "Pulse Core",
    "desc": "Recovered from Level 999.",
    "hook": "Found only at Depth 21.",
    "slot": "Armor",
    "rarity": "uncommon",
    "cost": 784526490225,
    "stats": { "clickMult": 1.49, "prodMult": 1.49, "luck": 0.154, "crit": 0.123 },
    "rating": 440,
    "levelIndex": 21,
  },
  {
    "id": "gear-l21-r2-trinket",
    "name": "Vacuum Charm",
    "desc": "Recovered from Level 999.",
    "hook": "Found only at Depth 21.",
    "slot": "Trinket",
    "rarity": "rare",
    "cost": 1046035320300,
    "stats": { "clickMult": 1.53, "prodMult": 1.53, "luck": 0.572, "crit": 0.244 },
    "rating": 660,
    "levelIndex": 21,
  },
  {
    "id": "gear-l21-r3-weapon",
    "name": "Zero Point",
    "desc": "Recovered from Level 999.",
    "hook": "Found only at Depth 21.",
    "slot": "Weapon",
    "rarity": "epic",
    "cost": 1307544150375,
    "stats": { "clickMult": 2.4, "prodMult": 1.47, "luck": 0.14, "crit": 0.449 },
    "rating": 880,
    "levelIndex": 21,
  },
  {
    "id": "gear-l21-r4-light",
    "name": "Event Crystal",
    "desc": "Recovered from Level 999.",
    "hook": "Found only at Depth 21.",
    "slot": "Light",
    "rarity": "legendary",
    "cost": 1569052980450,
    "stats": { "clickMult": 1.57, "prodMult": 2.7, "luck": 0.679, "crit": 0.136 },
    "rating": 1100,
    "levelIndex": 21,
  },
  {
    "id": "gear-l22-r0-armor",
    "name": "Prism Stone",
    "desc": "Recovered from Unnumbered Level - 'The Hub'.",
    "hook": "Found only at Depth 22.",
    "slot": "Armor",
    "rarity": "common",
    "cost": 1569052980450,
    "stats": { "clickMult": 1.41, "prodMult": 1.41, "luck": 0.129, "crit": 0.103 },
    "rating": 230,
    "levelIndex": 22,
  },
  {
    "id": "gear-l22-r1-trinket",
    "name": "Hologram Core",
    "desc": "Recovered from Unnumbered Level - 'The Hub'.",
    "hook": "Found only at Depth 22.",
    "slot": "Trinket",
    "rarity": "uncommon",
    "cost": 2353579470675,
    "stats": { "clickMult": 1.45, "prodMult": 1.45, "luck": 0.482, "crit": 0.206 },
    "rating": 460,
    "levelIndex": 22,
  },
  {
    "id": "gear-l22-r2-weapon",
    "name": "Fluorescent Shard",
    "desc": "Recovered from Unnumbered Level - 'The Hub'.",
    "hook": "Found only at Depth 22.",
    "slot": "Weapon",
    "rarity": "rare",
    "cost": 3138105960900,
    "stats": { "clickMult": 2.2, "prodMult": 1.4, "luck": 0.12, "crit": 0.382 },
    "rating": 690,
    "levelIndex": 22,
  },
  {
    "id": "gear-l22-r3-light",
    "name": "Glow Rod",
    "desc": "Recovered from Unnumbered Level - 'The Hub'.",
    "hook": "Found only at Depth 22.",
    "slot": "Light",
    "rarity": "epic",
    "cost": 3922632451125,
    "stats": { "clickMult": 1.49, "prodMult": 2.46, "luck": 0.586, "crit": 0.117 },
    "rating": 920,
    "levelIndex": 22,
  },
  {
    "id": "gear-l22-r4-armor",
    "name": "Voltage Charm",
    "desc": "Recovered from Unnumbered Level - 'The Hub'.",
    "hook": "Found only at Depth 22.",
    "slot": "Armor",
    "rarity": "legendary",
    "cost": 4707158941350,
    "stats": { "clickMult": 1.95, "prodMult": 1.95, "luck": 0.296, "crit": 0.236 },
    "rating": 1150,
    "levelIndex": 22,
  },
  {
    "id": "gear-l23-r0-trinket",
    "name": "Current Blade",
    "desc": "Recovered from Unnumbered Level - 'The Blue Channel'.",
    "hook": "Found only at Depth 23.",
    "slot": "Trinket",
    "rarity": "common",
    "cost": 4707158941350,
    "stats": { "clickMult": 1.38, "prodMult": 1.38, "luck": 0.402, "crit": 0.172 },
    "rating": 240,
    "levelIndex": 23,
  },
  {
    "id": "gear-l23-r1-weapon",
    "name": "Ripple Charm",
    "desc": "Recovered from Unnumbered Level - 'The Blue Channel'.",
    "hook": "Found only at Depth 23.",
    "slot": "Weapon",
    "rarity": "uncommon",
    "cost": 7060738412025,
    "stats": { "clickMult": 2.0, "prodMult": 1.33, "luck": 0.101, "crit": 0.322 },
    "rating": 480,
    "levelIndex": 23,
  },
  {
    "id": "gear-l23-r2-light",
    "name": "Tide Pearl",
    "desc": "Recovered from Unnumbered Level - 'The Blue Channel'.",
    "hook": "Found only at Depth 23.",
    "slot": "Light",
    "rarity": "rare",
    "cost": 9414317882700,
    "stats": { "clickMult": 1.42, "prodMult": 2.25, "luck": 0.498, "crit": 0.1 },
    "rating": 720,
    "levelIndex": 23,
  },
  {
    "id": "gear-l23-r3-armor",
    "name": "Abyss Pearl",
    "desc": "Recovered from Unnumbered Level - 'The Blue Channel'.",
    "hook": "Found only at Depth 23.",
    "slot": "Armor",
    "rarity": "epic",
    "cost": 11767897353375,
    "stats": { "clickMult": 1.81, "prodMult": 1.81, "luck": 0.255, "crit": 0.204 },
    "rating": 960,
    "levelIndex": 23,
  },
  {
    "id": "gear-l23-r4-trinket",
    "name": "Depth Stone",
    "desc": "Recovered from Unnumbered Level - 'The Blue Channel'.",
    "hook": "Found only at Depth 23.",
    "slot": "Trinket",
    "rarity": "legendary",
    "cost": 14121476824050,
    "stats": { "clickMult": 1.86, "prodMult": 1.86, "luck": 0.925, "crit": 0.394 },
    "rating": 1200,
    "levelIndex": 23,
  },
  {
    "id": "gear-l24-r0-weapon",
    "name": "Circuit Blade",
    "desc": "Recovered from Red Rooms.",
    "hook": "Found only at Depth 24.",
    "slot": "Weapon",
    "rarity": "common",
    "cost": 14121476824050,
    "stats": { "clickMult": 1.84, "prodMult": 1.28, "luck": 0.084, "crit": 0.268 },
    "rating": 250,
    "levelIndex": 24,
  },
  {
    "id": "gear-l24-r1-light",
    "name": "Prism Stone",
    "desc": "Recovered from Red Rooms.",
    "hook": "Found only at Depth 24.",
    "slot": "Light",
    "rarity": "uncommon",
    "cost": 21182215236075,
    "stats": { "clickMult": 1.35, "prodMult": 2.05, "luck": 0.418, "crit": 0.084 },
    "rating": 500,
    "levelIndex": 24,
  },
  {
    "id": "gear-l24-r2-armor",
    "name": "Sign Fragment",
    "desc": "Recovered from Red Rooms.",
    "hook": "Found only at Depth 24.",
    "slot": "Armor",
    "rarity": "rare",
    "cost": 28242953648100,
    "stats": { "clickMult": 1.69, "prodMult": 1.69, "luck": 0.216, "crit": 0.173 },
    "rating": 750,
    "levelIndex": 24,
  },
  {
    "id": "gear-l24-r3-trinket",
    "name": "Glow Rod",
    "desc": "Recovered from Red Rooms.",
    "hook": "Found only at Depth 24.",
    "slot": "Trinket",
    "rarity": "epic",
    "cost": 35303692060125,
    "stats": { "clickMult": 1.74, "prodMult": 1.74, "luck": 0.795, "crit": 0.339 },
    "rating": 1000,
    "levelIndex": 24,
  },
  {
    "id": "gear-l24-r4-weapon",
    "name": "Hologram Core",
    "desc": "Recovered from Red Rooms.",
    "hook": "Found only at Depth 24.",
    "slot": "Weapon",
    "rarity": "legendary",
    "cost": 42364430472150,
    "stats": { "clickMult": 2.93, "prodMult": 1.64, "luck": 0.193, "crit": 0.616 },
    "rating": 1250,
    "levelIndex": 24,
  },
  {
    "id": "gear-l25-r0-light",
    "name": "Keyboard Blade",
    "desc": "Recovered from The Manila Room.",
    "hook": "Found only at Depth 25.",
    "slot": "Light",
    "rarity": "common",
    "cost": 42364430472150,
    "stats": { "clickMult": 1.29, "prodMult": 1.87, "luck": 0.348, "crit": 0.07 },
    "rating": 260,
    "levelIndex": 25,
  },
  {
    "id": "gear-l25-r1-armor",
    "name": "Chair Leg Mace",
    "desc": "Recovered from The Manila Room.",
    "hook": "Found only at Depth 25.",
    "slot": "Armor",
    "rarity": "uncommon",
    "cost": 63546645708225,
    "stats": { "clickMult": 1.58, "prodMult": 1.58, "luck": 0.181, "crit": 0.145 },
    "rating": 520,
    "levelIndex": 25,
  },
  {
    "id": "gear-l25-r2-trinket",
    "name": "Desk Lamp Core",
    "desc": "Recovered from The Manila Room.",
    "hook": "Found only at Depth 25.",
    "slot": "Trinket",
    "rarity": "rare",
    "cost": 84728860944300,
    "stats": { "clickMult": 1.63, "prodMult": 1.63, "luck": 0.674, "crit": 0.288 },
    "rating": 780,
    "levelIndex": 25,
  },
  {
    "id": "gear-l25-r3-weapon",
    "name": "Printer Toner",
    "desc": "Recovered from The Manila Room.",
    "hook": "Found only at Depth 25.",
    "slot": "Weapon",
    "rarity": "epic",
    "cost": 105911076180375,
    "stats": { "clickMult": 2.65, "prodMult": 1.55, "luck": 0.165, "crit": 0.529 },
    "rating": 1040,
    "levelIndex": 25,
  },
  {
    "id": "gear-l25-r4-light",
    "name": "Monitor Shard",
    "desc": "Recovered from The Manila Room.",
    "hook": "Found only at Depth 25.",
    "slot": "Light",
    "rarity": "legendary",
    "cost": 127093291416450,
    "stats": { "clickMult": 1.67, "prodMult": 3.0, "luck": 0.8, "crit": 0.16 },
    "rating": 1300,
    "levelIndex": 25,
  },
  {
    "id": "gear-l26-r0-armor",
    "name": "Singularity Shard",
    "desc": "Recovered from Level 0.1 - 'Zenith Station'.",
    "hook": "Found only at Depth 26.",
    "slot": "Armor",
    "rarity": "common",
    "cost": 127093291416450,
    "stats": { "clickMult": 1.48, "prodMult": 1.48, "luck": 0.15, "crit": 0.12 },
    "rating": 270,
    "levelIndex": 26,
  },
  {
    "id": "gear-l26-r1-trinket",
    "name": "Event Crystal",
    "desc": "Recovered from Level 0.1 - 'Zenith Station'.",
    "hook": "Found only at Depth 26.",
    "slot": "Trinket",
    "rarity": "uncommon",
    "cost": 190639937124675,
    "stats": { "clickMult": 1.53, "prodMult": 1.53, "luck": 0.564, "crit": 0.241 },
    "rating": 540,
    "levelIndex": 26,
  },
  {
    "id": "gear-l26-r2-weapon",
    "name": "Zero Point",
    "desc": "Recovered from Level 0.1 - 'Zenith Station'.",
    "hook": "Found only at Depth 26.",
    "slot": "Weapon",
    "rarity": "rare",
    "cost": 254186582832900,
    "stats": { "clickMult": 2.4, "prodMult": 1.47, "luck": 0.14, "crit": 0.448 },
    "rating": 810,
    "levelIndex": 26,
  },
  {
    "id": "gear-l26-r3-light",
    "name": "Vacuum Charm",
    "desc": "Recovered from Level 0.1 - 'Zenith Station'.",
    "hook": "Found only at Depth 26.",
    "slot": "Light",
    "rarity": "epic",
    "cost": 317733228541125,
    "stats": { "clickMult": 1.57, "prodMult": 2.72, "luck": 0.686, "crit": 0.137 },
    "rating": 1080,
    "levelIndex": 26,
  },
  {
    "id": "gear-l26-r4-armor",
    "name": "Null Fragment",
    "desc": "Recovered from Level 0.1 - 'Zenith Station'.",
    "hook": "Found only at Depth 26.",
    "slot": "Armor",
    "rarity": "legendary",
    "cost": 381279874249350,
    "stats": { "clickMult": 2.11, "prodMult": 2.11, "luck": 0.346, "crit": 0.277 },
    "rating": 1350,
    "levelIndex": 26,
  },
  {
    "id": "gear-l27-r0-trinket",
    "name": "Printer Toner",
    "desc": "Recovered from Level 0.2 - 'Remodeled Mess'.",
    "hook": "Found only at Depth 27.",
    "slot": "Trinket",
    "rarity": "common",
    "cost": 381279874249350,
    "stats": { "clickMult": 1.44, "prodMult": 1.44, "luck": 0.468, "crit": 0.2 },
    "rating": 280,
    "levelIndex": 27,
  },
  {
    "id": "gear-l27-r1-weapon",
    "name": "Keyboard Blade",
    "desc": "Recovered from Level 0.2 - 'Remodeled Mess'.",
    "hook": "Found only at Depth 27.",
    "slot": "Weapon",
    "rarity": "uncommon",
    "cost": 571919811374025,
    "stats": { "clickMult": 2.17, "prodMult": 1.39, "luck": 0.117, "crit": 0.374 },
    "rating": 560,
    "levelIndex": 27,
  },
  {
    "id": "gear-l27-r2-light",
    "name": "Cabinet Plate",
    "desc": "Recovered from Level 0.2 - 'Remodeled Mess'.",
    "hook": "Found only at Depth 27.",
    "slot": "Light",
    "rarity": "rare",
    "cost": 762559748498700,
    "stats": { "clickMult": 1.48, "prodMult": 2.45, "luck": 0.58, "crit": 0.116 },
    "rating": 840,
    "levelIndex": 27,
  },
  {
    "id": "gear-l27-r3-armor",
    "name": "Stapler Cudgel",
    "desc": "Recovered from Level 0.2 - 'Remodeled Mess'.",
    "hook": "Found only at Depth 27.",
    "slot": "Armor",
    "rarity": "epic",
    "cost": 953199685623375,
    "stats": { "clickMult": 1.95, "prodMult": 1.95, "luck": 0.296, "crit": 0.237 },
    "rating": 1120,
    "levelIndex": 27,
  },
  {
    "id": "gear-l27-r4-trinket",
    "name": "Chair Leg Mace",
    "desc": "Recovered from Level 0.2 - 'Remodeled Mess'.",
    "hook": "Found only at Depth 27.",
    "slot": "Trinket",
    "rarity": "legendary",
    "cost": 1143839622748050,
    "stats": { "clickMult": 2.0, "prodMult": 2.0, "luck": 1.076, "crit": 0.459 },
    "rating": 1400,
    "levelIndex": 27,
  },
  {
    "id": "gear-l28-r0-weapon",
    "name": "Firewall Plate",
    "desc": "Recovered from Level 1.1 - 'Corrupted Corridor'.",
    "hook": "Found only at Depth 28.",
    "slot": "Weapon",
    "rarity": "common",
    "cost": 1143839622748050,
    "stats": { "clickMult": 1.97, "prodMult": 1.32, "luck": 0.097, "crit": 0.31 },
    "rating": 290,
    "levelIndex": 28,
  },
  {
    "id": "gear-l28-r1-light",
    "name": "Code Blade",
    "desc": "Recovered from Level 1.1 - 'Corrupted Corridor'.",
    "hook": "Found only at Depth 28.",
    "slot": "Light",
    "rarity": "uncommon",
    "cost": 1715759434122075,
    "stats": { "clickMult": 1.4, "prodMult": 2.21, "luck": 0.484, "crit": 0.097 },
    "rating": 580,
    "levelIndex": 28,
  },
  {
    "id": "gear-l28-r2-armor",
    "name": "Glitch Fragment",
    "desc": "Recovered from Level 1.1 - 'Corrupted Corridor'.",
    "hook": "Found only at Depth 28.",
    "slot": "Armor",
    "rarity": "rare",
    "cost": 2287679245496100,
    "stats": { "clickMult": 1.8, "prodMult": 1.8, "luck": 0.25, "crit": 0.2 },
    "rating": 870,
    "levelIndex": 28,
  },
  {
    "id": "gear-l28-r3-trinket",
    "name": "Pixel Shard",
    "desc": "Recovered from Level 1.1 - 'Corrupted Corridor'.",
    "hook": "Found only at Depth 28.",
    "slot": "Trinket",
    "rarity": "epic",
    "cost": 2859599056870125,
    "stats": { "clickMult": 1.86, "prodMult": 1.86, "luck": 0.921, "crit": 0.393 },
    "rating": 1160,
    "levelIndex": 28,
  },
  {
    "id": "gear-l28-r4-weapon",
    "name": "Cache Crystal",
    "desc": "Recovered from Level 1.1 - 'Corrupted Corridor'.",
    "hook": "Found only at Depth 28.",
    "slot": "Weapon",
    "rarity": "legendary",
    "cost": 3431518868244150,
    "stats": { "clickMult": 3.23, "prodMult": 1.74, "luck": 0.223, "crit": 0.713 },
    "rating": 1450,
    "levelIndex": 28,
  },
  {
    "id": "gear-l29-r0-light",
    "name": "Shadow Cloak",
    "desc": "Recovered from Level 1.3 - 'Malignance'.",
    "hook": "Found only at Depth 29.",
    "slot": "Light",
    "rarity": "common",
    "cost": 3431518868244150,
    "stats": { "clickMult": 1.33, "prodMult": 2.0, "luck": 0.401, "crit": 0.08 },
    "rating": 300,
    "levelIndex": 29,
  },
  {
    "id": "gear-l29-r1-armor",
    "name": "Ember Torch",
    "desc": "Recovered from Level 1.3 - 'Malignance'.",
    "hook": "Found only at Depth 29.",
    "slot": "Armor",
    "rarity": "uncommon",
    "cost": 5147278302366225,
    "stats": { "clickMult": 1.67, "prodMult": 1.67, "luck": 0.209, "crit": 0.167 },
    "rating": 600,
    "levelIndex": 29,
  },
  {
    "id": "gear-l29-r2-trinket",
    "name": "Whisper Charm",
    "desc": "Recovered from Level 1.3 - 'Malignance'.",
    "hook": "Found only at Depth 29.",
    "slot": "Trinket",
    "rarity": "rare",
    "cost": 6863037736488300,
    "stats": { "clickMult": 1.72, "prodMult": 1.72, "luck": 0.777, "crit": 0.331 },
    "rating": 900,
    "levelIndex": 29,
  },
  {
    "id": "gear-l29-r3-weapon",
    "name": "Dusk Crystal",
    "desc": "Recovered from Level 1.3 - 'Malignance'.",
    "hook": "Found only at Depth 29.",
    "slot": "Weapon",
    "rarity": "epic",
    "cost": 8578797170610375,
    "stats": { "clickMult": 2.9, "prodMult": 1.63, "luck": 0.19, "crit": 0.609 },
    "rating": 1200,
    "levelIndex": 29,
  },
  {
    "id": "gear-l29-r4-light",
    "name": "Blindfold Mask",
    "desc": "Recovered from Level 1.3 - 'Malignance'.",
    "hook": "Found only at Depth 29.",
    "slot": "Light",
    "rarity": "legendary",
    "cost": 10294556604732450,
    "stats": { "clickMult": 1.77, "prodMult": 3.3, "luck": 0.922, "crit": 0.184 },
    "rating": 1500,
    "levelIndex": 29,
  },
  {
    "id": "gear-l30-r0-armor",
    "name": "Room Key",
    "desc": "Recovered from Level 5.1 - 'GRAND OPENING OF THE TERROR HOTEL CASINO'.",
    "hook": "Found only at Depth 30.",
    "slot": "Armor",
    "rarity": "uncommon",
    "cost": 10294556604732450,
    "stats": { "clickMult": 1.69, "prodMult": 1.69, "luck": 0.216, "crit": 0.172 },
    "rating": 310,
    "levelIndex": 30,
  },
  {
    "id": "gear-l30-r1-trinket",
    "name": "Bell Hammer",
    "desc": "Recovered from Level 5.1 - 'GRAND OPENING OF THE TERROR HOTEL CASINO'.",
    "hook": "Found only at Depth 30.",
    "slot": "Trinket",
    "rarity": "rare",
    "cost": 15441834907098676,
    "stats": { "clickMult": 1.75, "prodMult": 1.75, "luck": 0.802, "crit": 0.342 },
    "rating": 620,
    "levelIndex": 30,
  },
  {
    "id": "gear-l30-r2-weapon",
    "name": "Chandelier Shard",
    "desc": "Recovered from Level 5.1 - 'GRAND OPENING OF THE TERROR HOTEL CASINO'.",
    "hook": "Found only at Depth 30.",
    "slot": "Weapon",
    "rarity": "epic",
    "cost": 20589113209464900,
    "stats": { "clickMult": 2.97, "prodMult": 1.66, "luck": 0.197, "crit": 0.629 },
    "rating": 930,
    "levelIndex": 30,
  },
  {
    "id": "gear-l30-r3-light",
    "name": "Bedpost Club",
    "desc": "Recovered from Level 5.1 - 'GRAND OPENING OF THE TERROR HOTEL CASINO'.",
    "hook": "Found only at Depth 30.",
    "slot": "Light",
    "rarity": "legendary",
    "cost": 25736391511831124,
    "stats": { "clickMult": 1.79, "prodMult": 3.38, "luck": 0.952, "crit": 0.19 },
    "rating": 1240,
    "levelIndex": 30,
  },
  {
    "id": "gear-l30-r4-armor",
    "name": "Carpet Square",
    "desc": "Recovered from Level 5.1 - 'GRAND OPENING OF THE TERROR HOTEL CASINO'.",
    "hook": "Found only at Depth 30.",
    "slot": "Armor",
    "rarity": "mythic",
    "cost": 30883669814197352,
    "stats": { "clickMult": 2.66, "prodMult": 2.66, "luck": 0.517, "crit": 0.414 },
    "rating": 1550,
    "levelIndex": 30,
    "abyssOnly": true,
  },
  {
    "id": "gear-l31-r0-trinket",
    "name": "Picket Stake",
    "desc": "Recovered from Level 6.1 - 'The Snackrooms'.",
    "hook": "Found only at Depth 31.",
    "slot": "Trinket",
    "rarity": "uncommon",
    "cost": 30883669814197352,
    "stats": { "clickMult": 1.62, "prodMult": 1.62, "luck": 0.667, "crit": 0.285 },
    "rating": 320,
    "levelIndex": 31,
  },
  {
    "id": "gear-l31-r1-weapon",
    "name": "Lawn Key",
    "desc": "Recovered from Level 6.1 - 'The Snackrooms'.",
    "hook": "Found only at Depth 31.",
    "slot": "Weapon",
    "rarity": "rare",
    "cost": 46325504721296032,
    "stats": { "clickMult": 2.66, "prodMult": 1.55, "luck": 0.166, "crit": 0.53 },
    "rating": 640,
    "levelIndex": 31,
  },
  {
    "id": "gear-l31-r2-light",
    "name": "Porch Lantern",
    "desc": "Recovered from Level 6.1 - 'The Snackrooms'.",
    "hook": "Found only at Depth 31.",
    "slot": "Light",
    "rarity": "epic",
    "cost": 61767339628394704,
    "stats": { "clickMult": 1.68, "prodMult": 3.03, "luck": 0.812, "crit": 0.162 },
    "rating": 960,
    "levelIndex": 31,
  },
  {
    "id": "gear-l31-r3-armor",
    "name": "Window Shard",
    "desc": "Recovered from Level 6.1 - 'The Snackrooms'.",
    "hook": "Found only at Depth 31.",
    "slot": "Armor",
    "rarity": "legendary",
    "cost": 77209174535493376,
    "stats": { "clickMult": 2.31, "prodMult": 2.31, "luck": 0.409, "crit": 0.328 },
    "rating": 1280,
    "levelIndex": 31,
  },
  {
    "id": "gear-l31-r4-trinket",
    "name": "Sidewalk Charm",
    "desc": "Recovered from Level 6.1 - 'The Snackrooms'.",
    "hook": "Found only at Depth 31.",
    "slot": "Trinket",
    "rarity": "mythic",
    "cost": 92651009442592064,
    "stats": { "clickMult": 2.5, "prodMult": 2.5, "luck": 1.602, "crit": 0.684 },
    "rating": 1600,
    "levelIndex": 31,
    "abyssOnly": true,
  },
  {
    "id": "gear-l32-r0-weapon",
    "name": "Sign Fragment",
    "desc": "Recovered from Level 11.3 - 'The Red Light District'.",
    "hook": "Found only at Depth 32.",
    "slot": "Weapon",
    "rarity": "uncommon",
    "cost": 92651009442592048,
    "stats": { "clickMult": 2.38, "prodMult": 1.46, "luck": 0.138, "crit": 0.44 },
    "rating": 330,
    "levelIndex": 32,
  },
  {
    "id": "gear-l32-r1-light",
    "name": "Circuit Blade",
    "desc": "Recovered from Level 11.3 - 'The Red Light District'.",
    "hook": "Found only at Depth 32.",
    "slot": "Light",
    "rarity": "rare",
    "cost": 138976514163888064,
    "stats": { "clickMult": 1.57, "prodMult": 2.71, "luck": 0.683, "crit": 0.137 },
    "rating": 660,
    "levelIndex": 32,
  },
  {
    "id": "gear-l32-r2-armor",
    "name": "Prism Stone",
    "desc": "Recovered from Level 11.3 - 'The Red Light District'.",
    "hook": "Found only at Depth 32.",
    "slot": "Armor",
    "rarity": "epic",
    "cost": 185302018885184096,
    "stats": { "clickMult": 2.12, "prodMult": 2.12, "luck": 0.349, "crit": 0.279 },
    "rating": 990,
    "levelIndex": 32,
  },
  {
    "id": "gear-l32-r3-trinket",
    "name": "Hologram Core",
    "desc": "Recovered from Level 11.3 - 'The Red Light District'.",
    "hook": "Found only at Depth 32.",
    "slot": "Trinket",
    "rarity": "legendary",
    "cost": 231627523606480128,
    "stats": { "clickMult": 2.18, "prodMult": 2.18, "luck": 1.266, "crit": 0.54 },
    "rating": 1320,
    "levelIndex": 32,
  },
  {
    "id": "gear-l32-r4-weapon",
    "name": "Fluorescent Shard",
    "desc": "Recovered from Level 11.3 - 'The Red Light District'.",
    "hook": "Found only at Depth 32.",
    "slot": "Weapon",
    "rarity": "mythic",
    "cost": 277953028327776128,
    "stats": { "clickMult": 4.3, "prodMult": 2.1, "luck": 0.33, "crit": 1.057 },
    "rating": 1650,
    "levelIndex": 32,
    "abyssOnly": true,
  },
  {
    "id": "gear-l33-r0-light",
    "name": "Whisper Charm",
    "desc": "Recovered from Unnumbered Level - 'Th3 Sh4dy Gr3y'.",
    "hook": "Found only at Depth 33.",
    "slot": "Light",
    "rarity": "uncommon",
    "cost": 277953028327776160,
    "stats": { "clickMult": 1.47, "prodMult": 2.42, "luck": 0.567, "crit": 0.113 },
    "rating": 340,
    "levelIndex": 33,
  },
  {
    "id": "gear-l33-r1-armor",
    "name": "Ember Torch",
    "desc": "Recovered from Unnumbered Level - 'Th3 Sh4dy Gr3y'.",
    "hook": "Found only at Depth 33.",
    "slot": "Armor",
    "rarity": "rare",
    "cost": 416929542491664256,
    "stats": { "clickMult": 1.94, "prodMult": 1.94, "luck": 0.293, "crit": 0.234 },
    "rating": 680,
    "levelIndex": 33,
  },
  {
    "id": "gear-l33-r2-trinket",
    "name": "Void Fragment",
    "desc": "Recovered from Unnumbered Level - 'Th3 Sh4dy Gr3y'.",
    "hook": "Found only at Depth 33.",
    "slot": "Trinket",
    "rarity": "epic",
    "cost": 555906056655552320,
    "stats": { "clickMult": 2.01, "prodMult": 2.01, "luck": 1.077, "crit": 0.46 },
    "rating": 1020,
    "levelIndex": 33,
  },
  {
    "id": "gear-l33-r3-weapon",
    "name": "Blindfold Mask",
    "desc": "Recovered from Unnumbered Level - 'Th3 Sh4dy Gr3y'.",
    "hook": "Found only at Depth 33.",
    "slot": "Weapon",
    "rarity": "legendary",
    "cost": 694882570819440384,
    "stats": { "clickMult": 3.61, "prodMult": 1.87, "luck": 0.261, "crit": 0.835 },
    "rating": 1360,
    "levelIndex": 33,
  },
  {
    "id": "gear-l33-r4-light",
    "name": "Shadow Cloak",
    "desc": "Recovered from Unnumbered Level - 'Th3 Sh4dy Gr3y'.",
    "hook": "Found only at Depth 33.",
    "slot": "Light",
    "rarity": "mythic",
    "cost": 833859084983328512,
    "stats": { "clickMult": 2.13, "prodMult": 4.4, "luck": 1.361, "crit": 0.272 },
    "rating": 1700,
    "levelIndex": 33,
    "abyssOnly": true,
  },
  {
    "id": "gear-l34-r0-armor",
    "name": "Glitch Fragment",
    "desc": "Recovered from Unnumbered Level - 'Deleted Level 14'.",
    "hook": "Found only at Depth 34.",
    "slot": "Armor",
    "rarity": "uncommon",
    "cost": 833859084983328512,
    "stats": { "clickMult": 1.78, "prodMult": 1.78, "luck": 0.243, "crit": 0.195 },
    "rating": 350,
    "levelIndex": 34,
  },
  {
    "id": "gear-l34-r1-trinket",
    "name": "Pixel Shard",
    "desc": "Recovered from Unnumbered Level - 'Deleted Level 14'.",
    "hook": "Found only at Depth 34.",
    "slot": "Trinket",
    "rarity": "rare",
    "cost": 1250788627474992640,
    "stats": { "clickMult": 1.84, "prodMult": 1.84, "luck": 0.904, "crit": 0.386 },
    "rating": 700,
    "levelIndex": 34,
  },
  {
    "id": "gear-l34-r2-weapon",
    "name": "Code Blade",
    "desc": "Recovered from Unnumbered Level - 'Deleted Level 14'.",
    "hook": "Found only at Depth 34.",
    "slot": "Weapon",
    "rarity": "epic",
    "cost": 1667718169966657024,
    "stats": { "clickMult": 3.22, "prodMult": 1.74, "luck": 0.222, "crit": 0.71 },
    "rating": 1050,
    "levelIndex": 34,
  },
  {
    "id": "gear-l34-r3-light",
    "name": "Cache Crystal",
    "desc": "Recovered from Unnumbered Level - 'Deleted Level 14'.",
    "hook": "Found only at Depth 34.",
    "slot": "Light",
    "rarity": "legendary",
    "cost": 2084647712458321408,
    "stats": { "clickMult": 1.89, "prodMult": 3.68, "luck": 1.074, "crit": 0.215 },
    "rating": 1400,
    "levelIndex": 34,
  },
  {
    "id": "gear-l34-r4-armor",
    "name": "Buffer Charm",
    "desc": "Recovered from Unnumbered Level - 'Deleted Level 14'.",
    "hook": "Found only at Depth 34.",
    "slot": "Armor",
    "rarity": "mythic",
    "cost": 2501577254949985280,
    "stats": { "clickMult": 2.87, "prodMult": 2.87, "luck": 0.584, "crit": 0.467 },
    "rating": 1750,
    "levelIndex": 34,
    "abyssOnly": true,
  },
  {
    "id": "gear-l35-r0-trinket",
    "name": "Echo Crystal",
    "desc": "Recovered from Level 611 - 'The maze, the creatures, the monster'.",
    "hook": "Found only at Depth 35.",
    "slot": "Trinket",
    "rarity": "uncommon",
    "cost": 2501577254949985280,
    "stats": { "clickMult": 1.7, "prodMult": 1.7, "luck": 0.75, "crit": 0.32 },
    "rating": 360,
    "levelIndex": 35,
  },
  {
    "id": "gear-l35-r1-weapon",
    "name": "Crystal Shard",
    "desc": "Recovered from Level 611 - 'The maze, the creatures, the monster'.",
    "hook": "Found only at Depth 35.",
    "slot": "Weapon",
    "rarity": "rare",
    "cost": 3752365882424977920,
    "stats": { "clickMult": 2.86, "prodMult": 1.62, "luck": 0.186, "crit": 0.595 },
    "rating": 720,
    "levelIndex": 35,
  },
  {
    "id": "gear-l35-r2-light",
    "name": "Stalactite Spear",
    "desc": "Recovered from Level 611 - 'The maze, the creatures, the monster'.",
    "hook": "Found only at Depth 35.",
    "slot": "Light",
    "rarity": "epic",
    "cost": 5003154509899970560,
    "stats": { "clickMult": 1.76, "prodMult": 3.28, "luck": 0.912, "crit": 0.182 },
    "rating": 1080,
    "levelIndex": 35,
  },
  {
    "id": "gear-l35-r3-armor",
    "name": "Fungus Lantern",
    "desc": "Recovered from Level 611 - 'The maze, the creatures, the monster'.",
    "hook": "Found only at Depth 35.",
    "slot": "Armor",
    "rarity": "legendary",
    "cost": 6253943137374963712,
    "stats": { "clickMult": 2.47, "prodMult": 2.47, "luck": 0.46, "crit": 0.368 },
    "rating": 1440,
    "levelIndex": 35,
  },
  {
    "id": "gear-l35-r4-trinket",
    "name": "Ore Fragment",
    "desc": "Recovered from Level 611 - 'The maze, the creatures, the monster'.",
    "hook": "Found only at Depth 35.",
    "slot": "Trinket",
    "rarity": "mythic",
    "cost": 7504731764849955840,
    "stats": { "clickMult": 2.68, "prodMult": 2.68, "luck": 1.8, "crit": 0.768 },
    "rating": 1800,
    "levelIndex": 35,
    "abyssOnly": true,
  },
];

export const ENCOUNTERS: Encounter[] = [
  {
    "id": "entity-3",
    "name": "Entity 3 - 'Smilers'",
    "desc": "Iconic darkness stalker controlled through light, noise, and eye contact.",
    "hook": "Let eye contact suppress pursuit while thrown lights create decoys or attract danger.",
    "boss": false,
    "rating": 242
  },
  {
    "id": "entity-8",
    "name": "Entity 8 - 'Hound'",
    "desc": "Fast common melee predator with readable growls and a brief eye-contact response.",
    "hook": "Use growls as an aggro warning and direct gaze as a short high-risk stagger.",
    "boss": false,
    "rating": 198
  },
  {
    "id": "entity-10",
    "name": "Entity 10 - 'Skin-Stealer'",
    "desc": "Skin-wearing mimic whose hunger state changes between docile and predatory behavior.",
    "hook": "Signal disguised mimics through translucent blood and food-reactive aggression.",
    "boss": false,
    "rating": 171
  },
  {
    "id": "entity-67",
    "name": "Entity 67 - 'Partygoers =)'",
    "desc": "Infectious Partygoer with a natural multi-stage weak-point combat sequence.",
    "hook": "Sever transforming arms, survive a berserk phase, then strike the opened chest or head.",
    "boss": false,
    "rating": 143
  },
  {
    "id": "entity-5",
    "name": "Entity 5 - 'Clump'",
    "desc": "Small high-speed vent ambusher that drags prey toward a central mouth.",
    "hook": "Use narrow geometry and a long grab limb to punish careless positioning.",
    "boss": false,
    "rating": 135
  },
  {
    "id": "entity-15",
    "name": "Entity 15 - 'Wretches'",
    "desc": "Former-human wretches embody the endpoint of failed survival-resource management.",
    "hook": "Turn prolonged hunger, thirst, sleeplessness, and isolation into a transformation threat.",
    "boss": false,
    "rating": 103
  },
  {
    "id": "entity-50",
    "name": "Entity 50 - 'The Numbed Man'",
    "desc": "Knowledge-linked hunter that becomes better able to locate anyone who reads about it.",
    "hook": "Make opening its lore entry advance a pursuit meter while revealing combat counters.",
    "boss": false,
    "rating": 86
  },
  {
    "id": "entity-2",
    "name": "Entity 2 - 'The Windows'",
    "desc": "Stationary cognitive trap manifesting personalized false exits.",
    "hook": "Generate tempting escape vistas from the player's goals and recent losses.",
    "boss": false,
    "rating": 57
  },
  {
    "id": "the-ghost-killer",
    "name": "The Ghost Killer",
    "desc": "Eyes of Argos assassin using knives, sais, throwing blades, and garrotes.",
    "hook": "Stage stalking encounters whose calling-card trophies reveal the target pattern.",
    "boss": false,
    "rating": 35
  },
  {
    "id": "entity-7",
    "name": "Entity 7 - 'Jerry'",
    "desc": "Unique tameable parrot and cult focus whose touch indoctrinates victims.",
    "hook": "Allow taming with seeds or Almond Water while cult influence creates a rival outcome.",
    "boss": true,
    "rating": 184
  },
  {
    "id": "entity-18",
    "name": "Entity 18 - 'The Beast of Level 5'",
    "desc": "Intelligent Terror Hotel owner suited to bargains, patronage, and recurring boss encounters.",
    "hook": "Make bargains with the hotel owner alter access, hostility, and the eventual boss fight.",
    "boss": true,
    "rating": 182
  },
  {
    "id": "partygoer-zero",
    "name": "Partygoer Zero",
    "desc": "Named Partygoer chimera suited to a multi-stage commander encounter.",
    "hook": "Combine human, crustacean, lamprey, centipede, and technological attacks across phases.",
    "boss": true,
    "rating": 72
  }
];

export const FINALE: Finale = {
  "id": "nostalgi-gaius",
  "name": "Unnumbered Entity - 'Nostalgi Gaius'",
  "desc": "Endgame infohazard and pursuer tied to Level 404 and dangerous knowledge.",
  "hook": "Increase encounter probability as the player learns and records more about the entity.",
  "rating": 199
};

export const PHENOMENA: Phenomenon[] = [
  {
    "id": "phenomenon-5",
    "name": "Phenomenon 5 - 'No-clipping'",
    "desc": "Core stable, conditional, or unpredictable teleportation through obstacles and levels.",
    "hook": "Use learned no-clip conditions as shortcuts while unstable attempts risk displacement.",
    "effect": "clickX2",
    "label": "Click power doubled",
    "rating": 126
  },
  {
    "id": "phenomenon-7",
    "name": "Phenomenon 7 - 'Liminal Echo'",
    "desc": "Psychic contamination that mutates environments and sustains global sanity pressure.",
    "hook": "Apply region-wide mental pressure that explains escalating environmental hostility.",
    "effect": "prodX2",
    "label": "Production doubled",
    "rating": 103
  },
  {
    "id": "phenomenon-2",
    "name": "Phenomenon 2 - 'Blood Moons'",
    "desc": "Timed blood-flood event telegraphed by red light and panic.",
    "hook": "Give five minutes to reach shelter or high ground before a level-wide flood.",
    "effect": "burst",
    "label": "Instant Almond Water burst",
    "rating": 49
  },
  {
    "id": "phenomenon-55",
    "name": "Phenomenon 55 - 'GODHAND'",
    "desc": "Violence-induced berserker state grants strength and euphoria while eroding humanity.",
    "hook": "Reward continued unarmed violence with power while escalating loss of control.",
    "effect": "clickX3",
    "label": "Click power tripled",
    "rating": 49
  },
  {
    "id": "phenomenon-13",
    "name": "Phenomenon 13 - 'A Way Out'",
    "desc": "Cult-controlled seven-step meditation allegedly returns people to the Frontrooms.",
    "hook": "Make escape depend on a morally uncertain ritual chain and unreliable guides.",
    "effect": "prodX3",
    "label": "Production tripled",
    "rating": 47
  },
  {
    "id": "phenomenon-15",
    "name": "Phenomenon 15 - 'Inversion'",
    "desc": "Color and audio warning precede a level-wide gravity reversal.",
    "hook": "Telegraph inversion clearly, then move combat and falling hazards onto the ceiling.",
    "effect": "luck",
    "label": "Fortune surges (loot & events)",
    "rating": 42
  },
  {
    "id": "phenomenon-32",
    "name": "Phenomenon 32 - 'Level Velocity'",
    "desc": "Moving levels collide, alter exits, expose regions, and destabilize collision.",
    "hook": "Change the world graph as level collisions open and close routes.",
    "effect": "clickX2",
    "label": "Click power doubled",
    "rating": 41
  },
  {
    "id": "phenomenon-99",
    "name": "Phenomenon 99 - 'Forced Immortality'",
    "desc": "Involuntary immortality causes instantaneous painful regeneration after attempted death.",
    "hook": "Use cursed regeneration to complicate death, sacrifice, and immortal NPC arcs.",
    "effect": "prodX2",
    "label": "Production doubled",
    "rating": 40
  },
  {
    "id": "phenomenon-9",
    "name": "Phenomenon 9 - 'The Blue Consumption'",
    "desc": "Three-stage lifecycle disintegrates, rearranges, and rebuilds an entire level.",
    "hook": "Transform a live region across seasonal phases of destruction, void drift, and reconstruction.",
    "effect": "burst",
    "label": "Instant Almond Water burst",
    "rating": 36
  },
  {
    "id": "phenomenon-86",
    "name": "Phenomenon 86 - 'The Great Backrooms Meteor Shower'",
    "desc": "Rare sanctuary event calms isolated people, cools the area, and suppresses hostility.",
    "hook": "Create a temporary nonviolent rest window during an otherwise desperate expedition.",
    "effect": "clickX3",
    "label": "Click power tripled",
    "rating": 34
  },
  {
    "id": "phenomenon-16",
    "name": "Phenomenon 16 - 'Destabilizing Storms'",
    "desc": "Reality storm rewrites matter, organisms, and physical laws with advance warning.",
    "hook": "Let players evacuate, mitigate, or exploit a storm that rerolls local rules and mutations.",
    "effect": "prodX3",
    "label": "Production tripled",
    "rating": 33
  },
  {
    "id": "phenomenon-23",
    "name": "Phenomenon 23 - 'No-Clip Fusion'",
    "desc": "No-clip collisions fuse beings into painful hybrids or explosive deaths.",
    "hook": "Create fusion enemies and player risks when multiple travelers share a destination.",
    "effect": "luck",
    "label": "Fortune surges (loot & events)",
    "rating": 32
  },
  {
    "id": "phenomenon-30",
    "name": "Phenomenon 30 - 'Orbs'",
    "desc": "Invisible space-time punctures detectable through flash photography and capable of draining life.",
    "hook": "Require camera flashes to reveal lethal orb density before crossing a route.",
    "effect": "clickX2",
    "label": "Click power doubled",
    "rating": 31
  },
  {
    "id": "phenomenon-50",
    "name": "Phenomenon 50 - 'Vortexes'",
    "desc": "Red-energy portals spread corruption, aggression, entities, and structural change.",
    "hook": "Grow corrupting portal zones until players contain them or face altered populations.",
    "effect": "prodX2",
    "label": "Production doubled",
    "rating": 31
  },
  {
    "id": "phenomenon-27",
    "name": "Phenomenon 27 - 'Phantom Sounds'",
    "desc": "Personalized source-less sounds cannot be reliably distinguished from real threats.",
    "hook": "Blend false footsteps, voices, machinery, and explosions into the genuine audio model.",
    "effect": "burst",
    "label": "Instant Almond Water burst",
    "rating": 29
  },
  {
    "id": "phenomenon-8",
    "name": "Phenomenon 8 - 'Doodletrapping'",
    "desc": "Marked paper teleports sleepers into explorable realms where drawings become interactive.",
    "hook": "Generate paper realms whose drawn objects become traversal tools or enemies.",
    "effect": "clickX3",
    "label": "Click power tripled",
    "rating": 13
  }
];

